### DISCUSSION TITLE
Use part of testcase result as url parameter

### DISCUSSION THREAD

**Discussion by p0wline** [ovh/venom#421] [Q&A] [answered]
Hi,

I need to filter one user id from the user list I get as a result of the first testcase in order to reuse it as a parameter in the url of the second testcase.
How should I do that ?

Here is the current content of the `.yml` file : 
```
 vars:
  # deleteuser.user : {{.get-user.result.Result.BodyJSON}}.filter((result, index) => if(result[index].first_name === "Leon"){return result[index].uuid})
  deleteuser.headers:
    content-type: "application/json"
    cookie: "xxx"
name:  delete user
testcases:
- name: get users
  steps:
  - type: http
    method: GET
    url: http://localhost:9000/users
    headers : {{.deleteuser.headers}}
    assertions:
      - result.statuscode ShouldEqual 200

# TODO get Leon's id
- name: delete one user
  steps:
  - type: http
    method: DELETE
    url: http://localhost:9000/users/{{.deleteuser.user}}
    assertions:
      - result.statuscode ShouldEqual 200
```

Thanks for your help.
