### DISCUSSION TITLE
Upload file - no such file

### DISCUSSION THREAD

**Discussion by mmfrxx** [ovh/venom#707] [Q&A] [answered]
Hi there!

I wanted to upload jpeg file and inserted it as:
`multipart_form:
    file: '@/file.jpeg;type=image/jpeg'`
where file.jpeg lies in the same folder as my test.yml file. However, when i run the test i get following response: `"bodyjson":{"error":"bad request error - http: no such file","success":false}`. I am doing HTTP POST request and running the test locally. Could you please help me to solve this problem? I am new to venom 

This is how testcase looks like
  - name: Test 
    steps:
      - type: http
        method: POST
        headers:
        url: {{.url}
        path: ?format=file
        multipart_form:
          file: '@./file.jpeg;type=image/jpeg'
        info: response {{.result}}
        assertions:
          - result.statuscode ShouldEqual 200
          - result.bodyjson.success ShouldEqual true

**Comment by ivan-velasco** [comment, marked as answer]
Try the following @mmfrxx 

```yml
name: Test
steps:
- type: http
  method: POST
  url: "{{.url}}"
  path: ?format=file
  multipart_form:
    file: '@{{.venom.testsuite.workdir}}/file.jpeg'
  info: 
  - "REQUEST body {{.result.request}}"
  - "RESPONSE body {{.result.bodyjson}}"
  assertions:
    - result.statuscode ShouldEqual 200
    - result.bodyjson.success ShouldEqual true
```
