### DISCUSSION TITLE
Delay

### DISCUSSION THREAD

**Discussion by cyberience** [ovh/venom#727] [Ideas]
Due to ddos protection I utilise delay functions on failure states, for this, it would be excellent if I can test for this, for example, if an action has a delay on an error, then its a pass.
I have trouble understanding the documents to get my tests working, for example where does it say to place _ charecters when there is a space in a json field? or how to create a delay between tests? maybe its obvious, and I am new to this tool, so any guidance is welcome.

**Comment by yesnault** [comment]
Hi, I'm not sure to understand the question, but some tips:
- when you exec venom run -vv, there are log files created. You will find variable inside them with the name that you can use in your testsuite files.
- About delay / retry, an example:
```yml
- name: Test with retries and delay in seconds between each try
  steps:
  - type: http
    method: GET
    url: https://eu.api.ovh.com/1.0/
    retry: 3
    retry_if: # (optional, lets you early break unrecoverable errors)
    - result.statuscode ShouldNotEqual 403
    delay: 2
    assertions:
    - result.statuscode ShouldEqual 200
  ```
Did you try that format? if it's not enough, you can compte retry / delay in a step 'exec' manually.

**Reply by cyberience** [reply]
Thanks for the reply. here is a sample, and based on your feed back, it looks like I must have the retry before the delay otherwise no delay.
```
name: Status
vars:
    targetStat: "http://localhost:9010/status"
    targetHelp: "http://localhost:9010/help"
    timeout: 20
testcases:
- name: Test Status
  steps:
      - type: http
        method: GET
        url: {{.targetStat}}
        timeout: {{.timeout}}
        retry: 1
        delay: 5
        assertions:
        - result.statuscode ShouldEqual 200
        - result.bodyjson.Database_Connected ShouldEqual true
        - result.bodyjson.Config_Loaded ShouldEqual true
- name: Test Help
  steps:
      - type: http
        method: GET
        url: {{.targetHelp}}
        timeout: {{.timeout}}
        retry: 1
        delay: 5
        assertions:
        - result.statuscode ShouldEqual 200

```
when I run them individually, ie manually, no problem, but in 2 seperate yml files, and venom run, they run to fast, so the api that has a ddos protection needs a 1 second delay between calls. placing them together in this format has the same issue. I got around it with a bash script as follows if it is useful to anyone, but would still like to do it right:
```
#!/bin/bash
export SCRIPTDIR=$PWD
rm *.log

for entry in `ls -v $SCRIPTDIR/*.yml`; do
    echo "Running : $entry "
    venom run $entry
    sleep 2
done
```
So looks like I was confused, and its now working, but just for the sake of others, I posted the reply here for reference, hope it helps.
