### DISCUSSION TITLE
Case insensitive assert

### DISCUSSION THREAD

**Discussion by AviranAbady** [ovh/venom#801] [Q&A] [answered]
Hey,

Looking at the following test suite, provided by oshp
https://github.com/oshp/oshp-validator/blob/main/tests_suite.yml

is it possible to have those assertions to be case insensitive

```yaml
 - name: Strict-Transport-Security
    steps:
      - type: http
        method: GET
        url: '{{.target_site}}'
        skip_body: true
        timeout: '{{.request_timeout_in_seconds}}'
        assertions:
          - result.statuscode ShouldEqual 200
          - result.headers.Strict-Transport-Security ShouldNotBeNil
          - result.headers.Strict-Transport-Security ShouldEqual "max-age=31536000; includeSubDomains"
```

Validate `Strict-Transport-Security` can be in any case, which may be the case in http 1.1+

**Comment by ivan-velasco** [comment, marked as answer]
@AviranAbady You could introduce a new assertion to handle the changing characters. Here's an approach if you know which characters will change:
```yml
  assertions:
    - result.statuscode ShouldEqual 200
    - result.headers.Strict-Transport-Security ShouldNotBeNil
    - or:
      - result.headers.Strict-Transport-Security ShouldEqual "max-age=31536000; includeSubDomains"
      - result.headers.Strict-Transport-Security ShouldEqual "Max-age=31536000; IncludeSubDomains"
```
