### ISSUE TITLE
Venom does not handle command output without \n

### ISSUE THREAD

**Issue by strokyl** [ovh/venom#140]
Sorry If I am not clear. I think example would be more understandable:
```
testcases:
  - name: echo
    steps:
      - script: echo "line"
        name: Testing that deploy return a valid curl command
        assertions:
          - result.code ShouldEqual 0
          - result.systemout ShouldContainSubstring "line"
```
This test work properly but if I replace echo by printf:
```
testcases:
  - name: command that does not return \n
    steps:
      - script: printf "line"
        name: Testing that deploy return a valid curl command
        assertions:
          - result.code ShouldEqual 0
          - result.systemout ShouldContainSubstring "line"
```
I got this following error:
```
# Failure: assertion: result.systemout ShouldContainSubstring "line"
Expected '' to contain substring 'line' (but it didn't)!
result.code: 0
result.err:
result.executor.script: printf "line"
result.systemerr:
result.systemerrjson:
result.systemout:
result.systemoutjson:
result.timehuman: 815.93µs
result.timeseconds: 0.00081593
```
The difference is that printf does not add '\n' whereas echo does.
