### ISSUE TITLE
shouldBeGreaterThan always valid

### ISSUE THREAD

**Issue by pierre-peronnet-ovh** [ovh/venom#144]
Hello,

When I am running venom with the following TestSuite, I get a success, whereas is obviously should not:

```yaml
name: test

testcases:
- name: echo0
  steps:
  - script: "echo 0"
  assertions:
  - result.systemout ShouldBeGreaterThan 1

- name: echo1
  steps:
  - script: "echo 1"
  assertions:
  - result.systemout ShouldBeGreaterThan 1

- name: echoEmpty
  steps:
  - script: "echo -n ''"
  assertions:
  - result.systemout ShouldBeGreaterThan 1
```

**Comment by fsamin** [comment]
sometimes yaml is not our friend, but he correct syntax should be:
```yaml
name: test

testcases:
- name: echo0
  steps:
  - script: "echo 0"
    assertions:
     - result.systemout ShouldBeGreaterThan 1

- name: echo1
  steps:
  - script: "echo 1"
    assertions:
     - result.systemout ShouldBeGreaterThan 1

- name: echoEmpty
  steps:
  - script: "echo -n ''"
    assertions:
     - result.systemout ShouldBeGreaterThan 1
```

with this syntax, the testsuite is correct
don't hesitate to reopen the issue if needed
