### ISSUE TITLE
executor http: failure on retry & timeout

### ISSUE THREAD

**Issue by yesnault** [ovh/venom#157]
```
- name: Foo
  steps:
  - type: http
    method: POST
    url: 'foo/service/{{.service.id}}'
    timeout: 5
    assertions:
    - result.statuscode ShouldEqual 200
    - result.bodyjson.id ShouldNotBeEmpty
    retry: 120
    delay: 2
    extracts:
      result.bodyjson.id: '{{id=.*}}'
```
if there is a timeout on the retry 10, all retry are done (it's ok), but the failure "timeout" is in result xml files.
