### ISSUE TITLE
Accept: */* causes: Error while unmarshal yml file

### ISSUE THREAD

**Issue by scraly** [ovh/venom#198]
Hi,

I've tried to add a common Accept header in a http executor : 

```
- name: TestToto
  steps:
  - type: http
    method: POST
    headers:
        Accept: */*
    url: "{{.toto}}/titi"
    retry: 1
    delay: 2
    assertions:
    - result.statuscode ShouldEqual 201
```

And it causes me an error:

`$ venom run
FATA[0000] Error while unmarshal file venom.yml err: yaml: line 37: did not find expected alphabetic or numeric character`

Thx
