### ISSUE TITLE
Force bash instead of shell for script execution

### ISSUE THREAD

**Issue by scraly** [ovh/venom#199]
Hi,

with exec executor I want to force the execution of a command (script) with bash instead of shell (in order to not have a "redirection unexpected" error.

How to do that?

Example:

```
- name: licenseToken
  steps:
  - type: exec
    script: myscript mycommand <<< "`cat sample`"
    assertions:
    - result.code ShouldEqual 0
```

--> will not work in shell but will work with bash

Thanks
