### ISSUE TITLE
skip test

### ISSUE THREAD

**Issue by fsamin** [ovh/venom#209]
Add ability to skip test against assertions

proposal:
```yaml
name: xxx

vars:
 foo: 'bar'

testcases:
- name: Title of First TestCase
  skip:
   - foo NotEqual bar
  steps:
  - script: echo '{{.foo}}'
    assertions:
    - result.code ShouldEqual 0
```

to do from #183
