### ISSUE TITLE
bug(http): default assertion is ignored causing all tests to success

### ISSUE THREAD

**Issue by nqb** [ovh/venom#249]
Hello

On venom 0.27, I noticed that when default assertion is not specified for `http` executor, all tests succeeded.

### Steps to reproduce
1. Create a `test_suite.yml` file
```yml
name: Test
version: 2
testcases:
  # will return SUCCESS and it should not because status code is 400
- name: http with default assertion not specify
  steps:
  - type: http
    method: GET
    url: http://httpbin.org/status/400

  # will return FAILED and it should because status code is 400
- name: http with default assertion specify
  steps:
  - type: http
    method: GET
    url: http://httpbin.org/status/400
    assertions:
      - result.statuscode ShouldEqual 200
```
2. Run test:
```
venom run test_suite.yml --log debug --output-dir $(mktemp -d) --format tap
```

### Actual results

First test succeeded, second test failed.
```
INFO[0000] Readingtest_suite.yml                        
INFO[0000] Parsing testsuite test_suite.yml             
INFO[0000] Readingtest_suite.yml                        
DEBU[0000] http.Run> Begin                               v.testsuite="Test [test_suite.yml]" x.testcase="http with default assertion not specify"
DEBU[0000] http.Run.doRequest> Begin                     v.testsuite="Test [test_suite.yml]" x.testcase="http with default assertion not specify"
DEBU[0000] http.Run.doRequest> End (0.297 seconds)       v.testsuite="Test [test_suite.yml]" x.testcase="http with default assertion not specify"
DEBU[0000] http.Run> End (0.298 seconds)                 v.testsuite="Test [test_suite.yml]" x.testcase="http with default assertion not specify"
DEBU[0000] http.Run> Begin                               v.testsuite="Test [test_suite.yml]" x.testcase="http with default assertion specify"
DEBU[0000] http.Run.doRequest> Begin                     v.testsuite="Test [test_suite.yml]" x.testcase="http with default assertion specify"
DEBU[0000] http.Run.doRequest> End (0.290 seconds)       v.testsuite="Test [test_suite.yml]" x.testcase="http with default assertion specify"
DEBU[0000] http.Run> End (0.290 seconds)                 v.testsuite="Test [test_suite.yml]" x.testcase="http with default assertion specify"
FAILURE test_suite.yml                                 589.791571ms

FAILED Test [test_suite.yml]
Failure in "test_suite.yml:19"
In test case "http with default assertion specify", at step 0
Assertion "result.statuscode ShouldEqual 200" failed
Expected: '200'
Actual:   '400'
(Should be equal)
Diff:     '2400'

Total:1 Duration:592.040194ms
OK:0
KO:1
Skipped:0
TestSuite:1
TestCase:2

File /tmp/tmp.o39fQ8Elln/test_results.tap is written
File /tmp/tmp.o39fQ8Elln/test.http-with-default-assertion-specify.dump is written
```

[Dump file](https://gist.github.com/nqb/c83e995eb8b7d7da1f3155280448993e)

### Expected results
First test case should failed

### Workaround

Specify default assertion like in second test case of this example
