### ISSUE TITLE
Extract variable on the fly from results

### ISSUE THREAD

**Issue by adam21** [ovh/venom#253]
I'm trying to extract a variable from result.bodyjson and use it in the next step of the same test, but the variable value is always 0 (zero).

My YAML:
```
- name: testA
  steps:
  - type: http
    method: POST
    url: "myurl"
    body: "{{.generate-full-licence-body.result.systemout}}"
    headers: 
      Authorization: "Bearer {{.getUserToken.result.systemout}}"
    assertions:
    - result.statuscode ShouldEqual 200
    - result.bodyjson.quantity ShouldEqual 3
    vars:
      qty: result.bodyjson.quantity
  - type: http
    method: GET
    url: "myurl"
    headers: 
      Authorization: "Bearer {{.getUserToken.result.systemout}}"
    assertions:
    - result.statuscode ShouldEqual 200
    - result.bodyjson.sugarquantity ShouldEqual "{{.testA.qty}}"
````

The assertion : 
```
Assertion "result.bodyjson.sugarquantity ShouldEqual \"{{.testA.qty}}\"" failed
Expected: '0'
Actual:   '3'
(Should be equal)
```
qty is always giving 0, I also tried to get value of other fields but the result was the same. 
Can someone help please ?
