### ISSUE TITLE
feat: support native YAML in vars file

### ISSUE THREAD

**Issue by nqb** [ovh/venom#256]
Currently, YAML dictionnaries should be formated like this:
```yaml
network.name: private
network.subnet: 172.17.1.0
```
in place of pure YAML:
```yaml
network:
  name: private
  subnet: 172.17.1.0
```
It means that it's not possible to reuse easily an existing YAML file with Venom. On top of that, it requires a lot of repetition.

**Comment by fsamin** [comment]
Hello, 
Do you have a full venom file example to illustrate it ?

**Comment by nqb** [comment]
Hello @fsamin,

This one is a YAML file from my point of view:
```yaml
---
network:
  name: private
  subnet: 172.17.1.0
```

With this file, I would like to be able to use a `var` like `{{.network.name}}` in a Venom test suite.
