### ISSUE TITLE
bug: Unable to access bodyjson key with variable if variable contains uppercase characters

### ISSUE THREAD

**Issue by miguelvr** [ovh/venom#261]
Example:

Response from `/id`

```json
{
  "id": "aBc123" 
}
```

Response from `/items`:
```json
{
  "aBc123": "important information"
}
```

example test.yaml

```yaml
name: example

testscases:
  - name: testA
    steps:
      - type: http
        method: GET
        url: localhost:8000/id
        vars:
          id:
            from: result.bodyjson.id
  - name: testB
    steps:
      - type: http
        method: GET
        url: localhost:8000/items
        assertions:
          - result.bodyjson.{{.testA.id}} ShouldEqual important information
```

This fails because the variable `{{.testA.id}}` will be in its original form and the access to `result.bodyjson` expects everything in lowercase
