### ISSUE TITLE
feat: Running same test case for list of inputs

### ISSUE THREAD

**Issue by miguelvr** [ovh/venom#263]
It would be nice to be able to set a list of inputs that would be run for the same testcase instead of having to repeat the same testcase N times.

Example:

```yaml
testcases:
  - name: testA
    inputs:
      - inputA: "1"
        inputB: "abc"
      - inputA: "2"
        inputB: "def"
    type: exec
    script: echo "first input is {{.inputA}}, second input is {{.inputB}}
```
