### ISSUE TITLE
Bug: wrong formating for number

### ISSUE THREAD

**Issue by wolf29f** [ovh/venom#270]
Hello,

When using a number returned from a previous step (eg: an id returned by an element creation), if the id is too long, when using it in another step it is rendered with scientific writing, which can cause trouble when testing (eg: updating a previously created element).

This behavior is pretty easy to reproduce, create a simple client, for example here's mine:

```go
func main() {

	server := http.Server{}
	server.Handler = http.HandlerFunc(func(resp http.ResponseWriter, req *http.Request) {
		resp.Header().Add("content-type", "application/json")
		data := map[string]interface{}{
			"id": 1167860,
		}
		respBody, err := json.Marshal(data)
		if err != nil {
			log.Error(err)
		}

		_, err = resp.Write(respBody)
		if err != nil {
			log.Error(err)
		}
	})
	server.Addr = "127.0.0.1:8080"
	server.ListenAndServe()
}
```

And a simple test file

```yml
name: "Test venom"
testcases:
  - name: "httpGet"
    steps:
      - type: http
        method: GET
        url: "http://127.0.0.1:8080"
        assertions:
          - "result.bodyjson.id ShouldEqual 1167860"
  - name: "print"
    steps:
      - type: exec
        script: >
          echo "Body content: '{{.httpGet.result.bodyjson.id}}'"
```

When running with debug log level we can see that the assertion for the http step work as expected, but the exec will print out `Body content: '1.16786e+06'` instead of `Body content: '1167860'`, the same happen when using the value in a URL.

**Comment by yesnault** [comment]
ref: https://github.com/ovh/venom/pull/279

**Comment by wolf29f** [comment]
Thanks for your work ! I tested your patch and it work well for the http executor, but I think the bug exists for all executors that decode JSON data, for example the problem is the same with the readfile executor :

Test file:
```yaml
name: Test
version: "2"
testcases:
  - name: "readfile"
    steps:
      - type: readfile
        path: testFile.json
        assertions:
          - "result.contentjson.bigint ShouldEqual 1234567890"
  - name: "print"
    steps:
      - type: exec
        script: >
          echo "Body content: '{{.readfile.result.contentjson.bigint}}'"

```

testFile.json:
```json
{
    "bigInt": 1234567890
}
```
