### ISSUE TITLE
Possibility to iterate over an array in a step

### ISSUE THREAD

**Issue by thibHamet** [ovh/venom#288]
It could be great to iterate over an array (declared in a variable or a result of a previous step) inside a step to test some different datasets.
Example : You have a first step that return an array

```YAML
name: test

testcases:

- name: getArray
  steps:
  - type: http
    method: GET
  ...
```

In the next step you want to iterate over the results 
```YAML
name: test

testcases:

- name: testOnAllArray
  steps:
  - loopover : result.getArray.bodyjson
  - loopvar : myData #take the value of the array element
  - type: http
    method: GET
    url : https://getmyid?id:eq={{.myData}}
  ...
```
