### ISSUE TITLE
Unable to use Kafka executor on master branch

### ISSUE THREAD

**Issue by matcornic** [ovh/venom#293]
Hello,

I'm trying to use Kafka executor with latest working version of Venom (master branch, cebd8782d675638f3bd40f59f89bb30b770ae656 at the creation time of this issue) with the following config:

```yml
        type: kafka
        clientType: consumer
        markOffset: true
        initialOffset: oldest
        groupID: venom
        addrs:
          - "{{.kafka_host}}:{{.kafka_port}}"
        topics:
          - "{{.kafka_my_topic}}"
```

It seems updating to latest Sarama had unwanted side effects.

```
/Users/mcornic/bin/venom run tests/venom/**/* --var-from-file ./tests/venom/vars-venom.yaml
[... other tests which not use Kafka executor...]
panic: non-positive interval for NewTicker

goroutine 85 [running]:
time.NewTicker(0x0, 0x0)
        /Users/mcornic/.gvm/gos/go1.15.3/src/time/tick.go:23 +0x151
github.com/bsm/sarama-cluster.(*Consumer).cmLoop(0xc000141a40, 0xc0000a6420)
        /Users/mcornic/pkg/mod/github.com/bsm/sarama-cluster@v2.1.15+incompatible/consumer.go:452 +0x5a
github.com/bsm/sarama-cluster.(*loopTomb).Go.func1(0xc0000c06c0, 0xc00051e0a0)
        /Users/mcornic/pkg/mod/github.com/bsm/sarama-cluster@v2.1.15+incompatible/util.go:73 +0x7b
created by github.com/bsm/sarama-cluster.(*loopTomb).Go
        /Users/mcornic/pkg/mod/github.com/bsm/sarama-cluster@v2.1.15+incompatible/util.go:69 +0x66
make: *** [integration] Error 2
```

It is working with latest release though
