### ISSUE TITLE
operator or in the definition of assertions

### ISSUE THREAD

**Issue by fsamin** [ovh/venom#312]

**Comment by yesnault** [comment]
```
 - name: foo
    steps:
      - script: echo "abc"
        assertions:
          - result.code ShouldEqual 0
          - or:
            - result.systemout ShouldContainSubstring "a"
            - result.systemout ShouldContainSubstring "b"
```

or

```
         - any:
            - result.systemout ShouldContainSubstring "a"
            - result.systemout ShouldContainSubstring "b"
```

**Comment by chmy-hp** [comment]
Great tool, The first thing I looked for after a run was the OR functionality

**Comment by lowlighter** [comment]
@fsamin If you're not currently working on this issue I can give it a shot if you're ok with that

I'd be tempted to go with the first syntax suggested by @yesnault, because we could expand easily to additional operators (I can see the `xor` being useful in some use cases, like asserting you got in a single case but not the other ones)
```yaml
assertions:
  - xor:
    - result.systemout ShouldContainSubstring "we got in case 1"
    - result.systemout ShouldContainSubstring "we got in case 2"
    - result.systemout ShouldContainSubstring "we got in case 3"
```

____

On another note, were you planning to support nested conditions too ? 
Not sure whether it's a wanted feature, but with the first syntax it could be eventually expanded to support an explicit `and` operator to handle cases like below:
```yaml
assertions:
  - or:
    - and: 
      - result.code ShouldEqual 0
      - result.systemout ShouldContainSubstring "success"
    - and: 
      - result.code ShouldNotEqual 0
      - result.systemout ShouldContainSubstring "error"
```
Though it may be over-complicated for not much gain :thinking:
