### ISSUE TITLE
Conditionals based on VENOM_VAR_*

### ISSUE THREAD

**Issue by cdelgehier** [ovh/venom#329]
It is sometimes useful to test the version of a package according to its OS, or the response of an API according to its version

The goal here is to write these tests but that some are not played on the `when` condition is not true

```
---
version: "2"

name: demo when 
vars:
  foo: bar

- name: TestCase with default value, exec cmd. Check if exit code != 1
  steps:
  - script: echo 'foo'
    type: exec
    when: foo IsEqual bar

- name: Title of First TestCase
  steps:
  - script: echo 'foo'
    assertions:
      - result.code ShouldEqual 0
    when: foo IsIn [bar,baz,plop]
...
```

The `when` could be on a step or on a testcase
