### ISSUE TITLE
bug(beta): variable assignment using environment variables doesn't work with --var-from-file

### ISSUE THREAD

**Issue by nqb** [ovh/venom#350]
On 1.0.0-beta.2, if you assign value to Venom variables using environment variables and `--var-from-file` option, variable values are not set.

See also #349 

### Steps to reproduce
1. Create a testsuite `env_vars_from_file.yml`:

```yml
name: Environment variables
version: 2
testcases:
- name: echo_timezone
  steps:
  - type: exec
    script: "echo {{.timezone}}"
    info: "{{.timezone}}"
```

2. Create `vars.yml` file:
```yml
---
timezone: "{{.TIMEZONE}}"
```
3. Run following commands:

```console
# TIMEZONE=UTC venom run env_vars.yml --var-from-file vars.yml 
Missing variables [TIMEZONE]

# VENOM_VAR_TIMEZONE=UTC venom run env_vars.yml --var-from-file vars.yml 
Missing variables [TIMEZONE]
```

### Expected results
- First Venom command failed according to #349 
- Second Venom command should succeed
