### ISSUE TITLE
Can't escape semi-colon in yaml templates assertions

### ISSUE THREAD

**Issue by LuisHudson25** [ovh/venom#357]
Hello,

I can't achieve to escape semi-colons in yaml templates in assertions, in theory double quote the value should be enough but I can't make it work, either the parser doesn't handle the case or I'm doing a mistake.

I'm using venom v0.27.0 with the following example:
```yaml
version: "2"

name: Test

testcases:
- name: Test
  steps:
  - script: "echo 'a: b'"
    assertions:
    -  result.systemout ShouldEqual "a: b"
    -  result.systemerr ShouldBeEmpty
```

I get the error:
```
error decoding assertions: 1 error(s) decoding:

* 'Assertions[0]' expected type 'string', got unconvertible type 'map[interface {}]interface {}'
```

Thanks you again for your work.
Luis

**Comment by fsamin** [comment]
Hello,

I also can reproduce it with the latest release, that i encourage you to test.

I will try to fix it, but as a workaround for now you can to write it this way:

```yaml
name: Test

testcases:
- name: Test
  steps:
  - script: "echo 'a: b'"
    assertions:
    -  "result.systemout ShouldEqual a: b"
    -  result.systemerr ShouldBeEmpty

```
