### ISSUE TITLE
UserExecutor output variable type ❓ 

### ISSUE THREAD

**Issue by manzan46** [ovh/venom#368]
👋  One related to #325 and user executor 

I don't seem to manage to return anything other than string type when using user executor.

For example in order to have a simplify custom http call (to avoid repeating header for example which are coming from env file)  I would like to have a user executor as follow: 

```
executor: customHTTP
input:
  path: {}
  method: {}
  body: {}
steps:
  - type: http
    method: "{{.input.method}}"
    url: "{{.input.BASE_URL}}{{.input.path}}"
    ignore_verify_ssl: true
    headers:
      "Content-Type": "{{.input.HTTP_CONTENT_TYPE}}"
      "Accept": "{{.input.HTTP_ACCEPT_HEADER}}"
      "User-Agent": "{{.input.HTTP_USER_AGENT}}"
      "Accept-Language": "{{.input.HTTP_ACCEPT_LANGUAGE}}"
    body: "{{.input.body}}"
output:
  statuscode: "{{.result.statuscode}}"
  bodyjson: "{{.result.bodyjson}}"
``` 

Then when I used this executor, here `statuscode`  work well but the `bodyjson` arrive as `{{.result.bodyjson}}` instead of a map, what would be even better is to simply forward the content of the result but not sure it's doable. 

Let me know if unclear.
