### ISSUE TITLE
user_executor inside user_executor, variables issue. 

### ISSUE THREAD

**Issue by manzan46** [ovh/venom#371]
👋🏻  We obliviously tried to use a user_executor inside an executor and it didn't work as variable generated as `input.input.foo`

For example:

```yaml
# env.yml file

foo: "foo"
```

```yaml
# testsuite_A.yml

name: testsuite A
testcases:
.... 
  steps:
  - type: userExecutorA
....
```

```yaml
# lib/user_executor_A.yml
executor: userExecutorA
steps:
- type: exec
  script: echo '{{.input.foo}}' ✅ 
  assertions:
  - result.code ShouldEqual 0
- type: userExecutorB
```

```yaml
# lib/user_executor_B.yml
executor: userExecutorB
steps:
- type: exec
  script: echo '{{.input.input.foo}}' # the input got double input. 
```

Proposal solution: 

https://github.com/ovh/venom/blob/master/types_executor.go#L179 similar to `venom` prefixed variables should not be re-prefixed :)

Happy to open PR if you think the proposal makes sense 🙏🏻

**Comment by yesnault** [comment]
Hi @manzan46, thank you for this detailed issue.

```bash
❯ ls -laRt
-rw-r--r--   1 yesnault  wheel   76  4 mar 10:33 testsuite_A.yml
drwxr-xr-x   4 yesnault  wheel  128  4 mar 10:29 lib
-rw-r--r--   1 yesnault  wheel   11  4 mar 10:28 env.yml

./lib:
-rw-r--r--  1 yesnault  wheel  119  4 mar 10:35 user_executor_B.yml
-rw-r--r--  1 yesnault  wheel  199  4 mar 10:35 user_executor_A.yml
````

files:

```
❯ cat env.yml
foo: "foo"
❯ cat testsuite_A.yml

name: testsuite A
testcases:
- name: mytc
  steps:
  - type: userExecutorA
❯ cat lib/user_executor_A.yml
executor: userExecutorA
input:
  foo: defaultValue
steps:
- type: exec
  script: echo '{{.input.foo}}' ✅
  assertions:
  - result.code ShouldEqual 0
- type: userExecutorB
  foob: '{{.input.foo}}'
❯ cat lib/user_executor_B.yml
executor: userExecutorB
input:
  foob: defaultValueB
steps:
- type: exec
  script: echo '{{.input.foob}}' > result.txt
```

run:

```bash
❯ venom run --var-from-file=env.yml testsuite_A.yml
 • testsuite A (testsuite_A.yml)
 	• mytc SUCCESS
❯ cat result.txt
foo
```

it's ok on master, feel free to reopen this issue if needed, maybe I forgot something in the case.

**Comment by manzan46** [comment]
@yesnault actually I think it's still not working even on master, the example you have reassigned  `foo` into `foob` for the second executor if you do exactly the same but without reassigning the input to another like below you'll see what I meant by the input.input: 

```
❯ cat env.yml
foo: "foo"

❯ cat testsuite_A.yml
name: testsuite A
testcases:
- name: mytc
  steps:
  - type: userExecutorA
 
❯ cat lib/user_executor_A.yml
executor: userExecutorA
input:
  foo: {}
steps:
- type: exec
  script: echo '{{.input.foo}}' ✅
  assertions:
  - result.code ShouldEqual 0
- type: userExecutorB
  foob: '{{.input.foo}}'

❯ cat lib/user_executor_B.yml
executor: userExecutorB
input:
  foo: {}
steps:
- type: exec
  script: echo 'input.foo {{.input.foo}}; input.input.foo {{.input.input.foo}}' > result.txt
```

```
> venom run --var-from-file=env.yml testsuite_A.yml
• testsuite A (mytc.yml)
 	• mytc SUCCESS
> cat result.txt                                                                                                                    
input.foo {}; input.input.foo foo
```

Let me know if it doesn't make sense :)
