### ISSUE TITLE
http user_executor  and body input issue

### ISSUE THREAD

**Issue by manzan46** [ovh/venom#381]
👋🏻  I have a small issue trying to create a user_executor with an HTTP executor for POST requests. 

I don't seem to be able to have a good format for the `body` fields

the test cases with multiple options but the first one that feels the nicest and work when using a HTTP executor straigh away: 
```yaml 
name: testsuite
vars:
  phone_number: "+3375{{ randNumeric 7 }}"
testcases:
- name: http_with_multiline_string
  steps:
  - type: my_custom_http
    method: POST
    url: "https://webhook.site/374406bd-c9a4-46a4-af4e-ae8beff66027"
    body: >-
      {
        "phone_number": "{{.input.phone_number}}"
      }
- name: http_with_double_quote_string
  steps:
  - type: my_custom_http
    method: POST
    url: "https://webhook.site/374406bd-c9a4-46a4-af4e-ae8beff66027"
    body: "{\"phone_number\": \"{{.input.phone_number}}\"}"
- name: http_with_single_quote_string
  steps:
  - type: my_custom_http
    method: POST
    url: "https://webhook.site/374406bd-c9a4-46a4-af4e-ae8beff66027"
    body: '{"phone_number": "{{.input.phone_number}}"}'
```

 and the custome executor: 
```yml
executor: my_custom_http
input:
  url: {}
  body: {}
  method: {}
steps:
- type: http
  method: "{{.input.method}}"
  body: "{{.input.body}}"
  url: "{{.input.url}}"
  headers: &headers_with_token
    "Content-Type": application/json"
  assertions:
    - .result.statuscode ShouldNotBeNil
output:
  statuscode: "{{.result.statuscode}}"
```

and the error I get each time: 
`[0mexecutor "my_custom_http" is not implemented as user executor - err:unable to parse file "/private/tmp/test_venom/lib/executorHTTP.yaml": error converting YAML to JSON: yaml: line 8: did not find expected key
`

I'm probably doing something wrong on this one 🙈

**Comment by yesnault** [comment]
ok with:

```
executor: my_custom_http
input:
  url: {}
  body: {}
  method: {}
steps:
- type: http
  method: '{{.input.method}}'
  body: '{{.input.body}}'
  url: '{{.input.url}}'
  assertions:
    - result.statuscode ShouldNotBeNil
output:
  statuscode: "{{.result.statuscode}}"

```
I'll add a tips in README to understand this kind of unmarshalling err.
