### ISSUE TITLE
Cannot check array in json response

### ISSUE THREAD

**Issue by amlwwalker** [ovh/venom#382]
In both an exec and HTTP test type, I am getting the same error:

```
    steps:
      - script: echo '{"foo":"bar", "allow_all":false, "some_arr":[]}'
        assertions:
          - result.systemoutjson.allow_all ShouldBeFalse
          - result.systemoutjson.some_arr ShouldBeEmpty
```
response
```
test_1           | Could not access "result.systemoutjson.some_arr" in assertion "result.systemoutjson.some_arr ShouldBeEmpty".
test_1           | This is what we have at "result.systemoutjson":
test_1           | {
test_1           |   "allow_all": false,
test_1           |   "some_arr": [],
test_1           |   "foo": "bar"
test_1           | }
```

Same issue with HTTP test.

Side note: are there any more filled out examples of using tests with http anywhere?
