### ISSUE TITLE
Multiline arg for custom executor

### ISSUE THREAD

**Issue by Thiht** [ovh/venom#392]
Hi,
I'm trying to create a custom executor following https://github.com/ovh/venom#user-defined-executors but multiline args don't seem to work :( 

Example with this custom executor:

```yml
executor: perl
input:
  script: 3
steps:
- type: exec
  script: |
    #!/usr/bin/perl
    use 5.010;
    use strict;
    use warnings;

    use JSON;

    my $json = {
      a => "{{.input.script}}"
    };

    print encode_json $json;
  assertions:
  - result.code ShouldEqual 0
output:
  all: '{{.result.systemoutjson}}'
```

The following test works:

```yml
name: testsuite with a user executor
testcases:
- name: testA
  steps:
  - type: perl
    script: 4
    assertions:
    - result.alljson.a ShouldEqual 4
```

> venom run test.yml
> • testsuite with a user executor (test.yml)
>        • testA SUCCESS

but if I replace the script with a multiline yml string it fails:

```yml
name: testsuite with a user executor
testcases:
- name: testA
  steps:
  - type: perl
    script: |
      4
    assertions:
    - result.alljson.a ShouldEqual 4
```

> venom run test.yml
> • testsuite with a user executor (test.yml)
>        • testA FAILURE
>Testcase "testA", step #0: Assertion "result.alljson.a ShouldEqual 4" failed. expected: 4  got: 3 (test.yml:9)
