### ISSUE TITLE
Got `template: input:1: unexpected "{" in command` after fetching PNG image

### ISSUE THREAD

**Issue by reno-xjb** [ovh/venom#409]
When fetching some PNG images in a step, next steps fail with `template: input:1: unexpected "{" in command` due to the image bytes being put in vars. I suspect this is an escaping issue, but I haven't dig too much into code to be sure.

A simple test suite to reproduce:
```
name: TestSuite
testcases:
- name: getImage
  steps:
  - type: http
    method: GET
    url: 'http://imgs.xkcd.com/comics/self_driving_issues.png'
    assertions:
    - result.statuscode ShouldEqual 200
- name: getImageAgain
  steps:
  - type: http
    method: GET
    url: 'http://imgs.xkcd.com/comics/self_driving_issues.png'
    assertions:
    - result.statuscode ShouldEqual 200

```
