### ISSUE TITLE
vars behave differently (depending on where they come from) in skip clause

### ISSUE THREAD

**Issue by guoweis-outreach** [ovh/venom#417]
I noticed that when specifying things in skip clause, it behaves differently between vars from --var-from-file and vars from environ var like `export VENOM_VAR_SOMEVAR`.

For these from --var-from-file, I could directly use them like
```yaml
skip:
  - someVar ShouldEqual someValue
```

However, if the var is from environment variable, I have to do one level indirection.

```yaml
vars:
  ut: "{{.someVar}}"

testcases:
  - name: SomeTestCases
    skip:
      - ut ShouldEqual someValue
```

If I just use someVar (from environ var), it'll never work.

**Comment by yesnault** [comment]
hi @guoweis-outreach , do you have a 'ready-to-run' yml test with the use case please ?

**Comment by yesnault** [comment]
Hi, I can't reproduce the issue, with the following testsuite:

```yml
---
name: a
version: 2

testcases:
- name: myvar_first
  steps:
  - type: exec
    script: "echo myvar {{.somevar2}}"
    info: "{{.result.systemout}}"
  skip:
  - somevar2 ShouldEqual ggg
```

```sh
❯ export VENOM_VAR_somevar2=ggg
❯ venom -vv run a.yml
          [trac] writing venom.log
 • a (a.yml)
        • myvar_first
                • exec SUCCESS
                  [info] myvar ggg

❯ export VENOM_VAR_somevar2=ggg2
❯ venom -vv run a.yml
          [trac] writing venom.0.log
 • a (a.yml)
        • myvar_first
```
