### ISSUE TITLE
Behavior of custom executor http json array in output

### ISSUE THREAD

**Issue by manzan46** [ovh/venom#425]
👋🏻  we are using a generic custom executor to make HTTP call and then return the response body, it all works well but we have an issue with HTTP array.

To reproduce example: 

`lib/get_http.yml`
```yml
executor: get_http
input:
  url: {}
steps:
- type: http
  method: GET
  url: "{{.input.url}}"
  assertions:
    - result.bodyjson.__type__ ShouldEqual Array
    - result.bodyjson.__len__ ShouldBeGreaterThanOrEqualTo 1
    - result.bodyjson.bodyjson0 ShouldNotBeNil
output:
  statuscode: "{{.result.statuscode}}"
  body: "{{.result.bodyjson}}" // similar behavior with "{{.result.body}}" 
```

`test.yml`
```yml
name: HTTP array testsuite
testcases:
- name: get http testcase
  steps:
  - type: get_http
    url: https://venom.free.beeceptor.com/array
    assertions:
      - result.statuscode ShouldEqual 200
      - result.bodyjson.__type__ ShouldEqual Array
      - result.bodyjson.__len__ ShouldBeGreaterThanOrEqualTo 1
      # Expected to work but Fail
      - result.bodyjson.bodyjson0 ShouldNotBeNil
      # Work but doesn't feel rigth
      - result.bodyjson.result.bodyjson0 ShouldNotBeNil

```

the answer of `https://venom.free.beeceptor.com/array`:

```json
[
  {
    "category": "passenger_problem",
     "id": "sanitary",
     "message": "Passenger didn't respect sanitary rules"
  },
  {
    "category": "passenger_no_show",
    "id": "passenger_no_show",
    "message": "Passenger not here"
   }
]
```

❓ Is there something we are missing or doing wrong? we basically would like to have the custom executor returning whatever it received, it seems to work well for other formats of JSON.  🙏🏻 

<details>
  <summary>logs</summary>

```json
{
 "variables": {
  "": "{\"\":\"{\\\"\\\":\\\"null\\\",\\\"__Len__\\\":\\\"0\\\",\\\"__Type__\\\":\\\"Map\\\",\\\"venom.testsuite\\\":\\\"HTTP array testsuite\\\",\\\"venom.testsuite.filename\\\":\\\"test.yml\\\",\\\"venom.testsuite.shortName\\\":\\\"HTTP array testsuite\\\",\\\"venom.testsuite.workdir\\\":\\\"/private/tmp/venom\\\"}\",\"__Len__\":\"6\",\"__Type__\":\"Map\",\"input.\":\"{\\\"\\\":\\\"{\\\\\\\"\\\\\\\":\\\\\\\"null\\\\\\\",\\\\\\\"__Len__\\\\\\\":\\\\\\\"0\\\\\\\",\\\\\\\"__Type__\\\\\\\":\\\\\\\"Map\\\\\\\",\\\\\\\"venom.testsuite\\\\\\\":\\\\\\\"HTTP array testsuite\\\\\\\",\\\\\\\"venom.testsuite.filename\\\\\\\":\\\\\\\"test.yml\\\\\\\",\\\\\\\"venom.testsuite.shortName\\\\\\\":\\\\\\\"HTTP array testsuite\\\\\\\",\\\\\\\"venom.testsuite.workdir\\\\\\\":\\\\\\\"/private/tmp/venom\\\\\\\"}\\\",\\\"__Len__\\\":\\\"6\\\",\\\"__Type__\\\":\\\"Map\\\",\\\"venom.testcase\\\":\\\"get-http-testcase\\\",\\\"venom.testsuite\\\":\\\"HTTP array testsuite\\\",\\\"venom.testsuite.filename\\\":\\\"test.yml\\\",\\\"venom.testsuite.shortName\\\":\\\"HTTP array testsuite\\\",\\\"venom.testsuite.workdir\\\":\\\"/private/tmp/venom\\\"}\",\"input.__Len__\":\"7\",\"input.__Type__\":\"Map\",\"input.input\":\"{\\\"url\\\":{}}\",\"input.url\":\"https://venom.free.beeceptor.com/array\",\"venom.executor.filename\":\"/private/tmp/venom/lib/executor.yml\",\"venom.executor.name\":\"get_http\",\"venom.testcase\":\"get_http\",\"venom.testsuite\":\"HTTP array testsuite\",\"venom.testsuite.filename\":\"test.yml\",\"venom.testsuite.shortName\":\"HTTP array testsuite\",\"venom.testsuite.workdir\":\"/private/tmp/venom\"}",
  "__Len__": "14",
  "__Type__": "Map",
  "input.": "{\"\":\"{\\\"\\\":\\\"null\\\",\\\"__Len__\\\":\\\"0\\\",\\\"__Type__\\\":\\\"Map\\\",\\\"venom.testsuite\\\":\\\"HTTP array testsuite\\\",\\\"venom.testsuite.filename\\\":\\\"test.yml\\\",\\\"venom.testsuite.shortName\\\":\\\"HTTP array testsuite\\\",\\\"venom.testsuite.workdir\\\":\\\"/private/tmp/venom\\\"}\",\"__Len__\":\"6\",\"__Type__\":\"Map\",\"venom.testcase\":\"get-http-testcase\",\"venom.testsuite\":\"HTTP array testsuite\",\"venom.testsuite.filename\":\"test.yml\",\"venom.testsuite.shortName\":\"HTTP array testsuite\",\"venom.testsuite.workdir\":\"/private/tmp/venom\"}",
  "input.__Len__": "7",
  "input.__Type__": "Map",
  "input.input": "{\"url\":{}}",
  "input.url": "https://venom.free.beeceptor.com/array",
  "venom.executor.filename": "/private/tmp/venom/lib/executor.yml",
  "venom.executor.name": "get_http",
  "venom.testcase": "get_http",
  "venom.testsuite": "HTTP array testsuite",
  "venom.testsuite.filename": "test.yml",
  "venom.testsuite.shortName": "HTTP array testsuite",
  "venom.testsuite.workdir": "/private/tmp/venom"
 },
 "step": {
  "assertions": [
   "result.bodyjson.__type__ ShouldEqual Array",
   "result.bodyjson.__len__ ShouldBeGreaterThanOrEqualTo 1",
   "result.bodyjson.bodyjson0 ShouldNotBeNil"
  ],
  "method": "GET",
  "type": "http",
  "url": "https://venom.free.beeceptor.com/array"
 },
 "result": {
  "timeseconds": 0.894535622,
  "statuscode": 200,
  "request": {
   "method": "GET",
   "url": "https://venom.free.beeceptor.com/array"
  },
  "body": "[{\"category\": \"passenger_problem\",\"id\": \"sanitary\",\"message\": \"Passenger didn't respect sanitary rules\"},{\"category\": \"passenger_no_show\",\"id\": \"passenger_no_show\",\"message\": \"Passenger not here\"}]",
  "bodyjson": [
   {
    "category": "passenger_problem",
    "id": "sanitary",
    "message": "Passenger didn't respect sanitary rules"
   },
   {
    "category": "passenger_no_show",
    "id": "passenger_no_show",
    "message": "Passenger not here"
   }
  ],
  "headers": {
   "Access-Control-Allow-Origin": "*",
   "Content-Type": "application/json",
   "Date": "Wed, 01 Sep 2021 05:54:58 GMT",
   "Vary": "Accept-Encoding"
  }
 }
}
```

```json
{
 "variables": {
  "": "{\"\":\"{\\\"\\\":\\\"null\\\",\\\"__Len__\\\":\\\"0\\\",\\\"__Type__\\\":\\\"Map\\\",\\\"venom.testsuite\\\":\\\"HTTP array testsuite\\\",\\\"venom.testsuite.filename\\\":\\\"test.yml\\\",\\\"venom.testsuite.shortName\\\":\\\"HTTP array testsuite\\\",\\\"venom.testsuite.workdir\\\":\\\"/private/tmp/venom\\\"}\",\"__Len__\":\"6\",\"__Type__\":\"Map\",\"venom.testcase\":\"get-http-testcase\",\"venom.testsuite\":\"HTTP array testsuite\",\"venom.testsuite.filename\":\"test.yml\",\"venom.testsuite.shortName\":\"HTTP array testsuite\",\"venom.testsuite.workdir\":\"/private/tmp/venom\"}",
  "__Len__": "7",
  "__Type__": "Map",
  "venom.testcase": "get-http-testcase",
  "venom.testsuite": "HTTP array testsuite",
  "venom.testsuite.filename": "test.yml",
  "venom.testsuite.shortName": "HTTP array testsuite",
  "venom.testsuite.workdir": "/private/tmp/venom"
 },
 "step": {
  "assertions": [
   "result.statuscode ShouldEqual 200",
   "result.bodyjson.__type__ ShouldEqual Array",
   "result.bodyjson.__len__ ShouldBeGreaterThanOrEqualTo 1",
   "result.bodyjson.bodyjson0 ShouldNotBeNil",
   "result.bodyjson.result.bodyjson0 ShouldNotBeNil"
  ],
  "type": "get_http",
  "url": "https://venom.free.beeceptor.com/array"
 },
 "result": {
  "": {
   "result": {
    "body": "[{\"category\": \"passenger_problem\",\"id\": \"sanitary\",\"message\": \"Passenger didn't respect sanitary rules\"},{\"category\": \"passenger_no_show\",\"id\": \"passenger_no_show\",\"message\": \"Passenger not here\"}]",
    "statuscode": "200"
   }
  },
  "__len__": 1,
  "__len__json": 1,
  "__type__": "Map",
  "json": {
   "result": {
    "body": "[{\"category\": \"passenger_problem\",\"id\": \"sanitary\",\"message\": \"Passenger didn't respect sanitary rules\"},{\"category\": \"passenger_no_show\",\"id\": \"passenger_no_show\",\"message\": \"Passenger not here\"}]",
    "statuscode": "200"
   }
  },
  "result": {
   "body": "[{\"category\": \"passenger_problem\",\"id\": \"sanitary\",\"message\": \"Passenger didn't respect sanitary rules\"},{\"category\": \"passenger_no_show\",\"id\": \"passenger_no_show\",\"message\": \"Passenger not here\"}]",
   "statuscode": "200"
  },
  "result.__len__": 2,
  "result.__len__json": 2,
  "result.__type__": "Map",
  "result.body": "[{\"category\": \"passenger_problem\",\"id\": \"sanitary\",\"message\": \"Passenger didn't respect sanitary rules\"},{\"category\": \"passenger_no_show\",\"id\": \"passenger_no_show\",\"message\": \"Passenger not here\"}]",
  "result.bodyjson": [
   {
    "category": "passenger_problem",
    "id": "sanitary",
    "message": "Passenger didn't respect sanitary rules"
   },
   {
    "category": "passenger_no_show",
    "id": "passenger_no_show",
    "message": "Passenger not here"
   }
  ],
  "result.statuscode": "200",
  "result.statuscodejson": 200,
  "resultjson": {
   "body": "[{\"category\": \"passenger_problem\",\"id\": \"sanitary\",\"message\": \"Passenger didn't respect sanitary rules\"},{\"category\": \"passenger_no_show\",\"id\": \"passenger_no_show\",\"message\": \"Passenger not here\"}]",
   "statuscode": "200"
  }
 }
}
```
</details>
