### ISSUE TITLE
Readfile executor does not work with fullpath

### ISSUE THREAD

**Issue by tomadele** [ovh/venom#435]
Hi,

I was using the readfile executor as such:

```yaml
  - name: Read output file
    steps:
      - type: readfile
        path: /path/to/my/csv/file.csv
        assertions:
          - result.err ShouldBeEmpty

          - result.content ShouldStartWith ...
```

But as I executed my tests, venom tried to read my file as:
```bash
path/to/the/venom/file/path/to/my/csv/file.csv # workdir path + specified path
```
instead of:
```bash
/path/to/my/csv/file.csv
```
However, your examples state that it should work (https://github.com/ovh/venom/tree/master/executors/readfile) but when I take a look at the code, it does not seem to allow fullpath to work properly: https://github.com/ovh/venom/blob/master/executors/readfile/readfile.go#L91

Since we can't modify workdir, according to [this](https://github.com/ovh/venom/issues/400) issue, I have to bypass it by using:
```yaml
  - name: Read output file
    steps:
      - type: exec
        script: cat /path/to/my/csv/file.csv
    assertions:
      - result.err ShouldBeEmpty

      - result.systemout ShouldStartWith ...
```
