### ISSUE TITLE
bug: test_results file is incorrect when --stop-on-failure is used

### ISSUE THREAD

**Issue by nqb** [ovh/venom#443]
On Venom 1.0.0-rc7, if you use `--stop-on-failure` option on a test suite, first test that failed stop the test suite but `test_results` file marked all other tests of the test suite as done with success.

### Steps to reproduce

1. Create following test suite
```
cat > a.yml << EOF
name: a
version: 2
testcases:
- name: failed
  steps:
  - type: exec
    script: "/bin/false"

- name: succeed
  steps:
  - type: exec
    script: "echo success > a.log"
EOF
```
2. Run: `venom run --output-dir=results --stop-on-failure --format=tap a.yml`

### Actual results

```console
# venom run --output-dir=results  --stop-on-failure --format=tap a.yml
 • a (a.yml)
        • failed FAILURE
Testcase "failed", step #0: Assertion "result.code ShouldEqual 0" failed. expected: 0  got: 1 (a.yml:0)
Writing file results/test_results.tap
```

`test_results.tap` contains:

```
TAP version 13
1..1
not ok 1 - a / failed
# Failure: Testcase "failed", step #0: Assertion "result.code ShouldEqual 0" failed. expected: 0  got: 1 (a.yml:0)
ok 2 - a / succeed
```

There is no `a.log` file created.

### Expected results
`test_results` file should not include tests skipped.
