### ISSUE TITLE
HTTP Executor JSON decoder fix #279 introduced an issue

### ISSUE THREAD

**Issue by jtbonhomme** [ovh/venom#449]
Hello,

I am afraid the #279 modification of the http executor number decoding introduced a regression using less than and greater than assertion with JSON body results.

Consider this simple test:
```yml
name: bodyjson assert comparator test
testcases:
- name: 'credit assert comparator'
  steps:
  - type: http
    method: GET
    url: https://eu.api.ovh.com/1.0/sms/rates/destinations?billingCountry=fr&country=fr
    headers:
      Content-type: application/json
    assertions:
    - result.bodyjson.credit ShouldBeLessThan 2
```

Running this test with this command fails (while credit is actually 1)
```shell
$ go run cmd/venom/main.go run ovh.yml -vv
          [trac] writing reports/venom.log
 • bodyjson assert comparator test (ovh.yml)
        • credit-assert-comparator FAILURE
          [trac] writing reports/bodyjson-assert-comparator-test.credit-assert-comparator.step.0.dump.json
Testcase "credit assert comparator", step #0: Assertion "result.bodyjson.credit ShouldBeLessThan 2" failed. This assertion requires 2 values of same types. (ovh.yml:11)
Writing file reports/test_results.
exit status 2
```

When the `decode.UseNumber()` call has been added to [http executor `Run()` function](https://github.com/ovh/venom/blob/227f6d31a5a3aaa88bc24cac7d591247858ad7af/executors/http/http.go#L227), it changed the way the assertions [function `areSameTypes()`](https://github.com/ovh/venom/blob/227f6d31a5a3aaa88bc24cac7d591247858ad7af/assertions/helper.go#L51) works.
When the assertion engine compares the result of the http call (credit == 1) and the comparison value in the test (should be less than 2), it actually compares an `interface {}(encoding/json.Number)` (from the json body decoding) against an `interface {}(string)` (from the test expected argument of the `ShouldBeLessThan` assertion.

Would you consider offer an option to use the `UseNumber()` function or not?
