### ISSUE TITLE
Add support for referencing result from previous steps within same `TestCase` context

### ISSUE THREAD

**Issue by lowlighter** [ovh/venom#451]
Currently supported (from https://github.com/ovh/venom#how-to-use-outputs-from-a-test-step-as-input-of-another-test-step):
```yaml
testcases:
- name: testA
  steps:
  - type: exec
    script: echo 'foo with a bar here'
    vars:
      myvariable:
        from: result.systemout

- name: testB
  steps:
  - type: exec
    script: echo {{.testA.myvariable}} 
```

However, it's actually support for cross-tests referencing, not cross-steps referencing.
It means that in a custom executor environment, there's no workaround to achieve the following:

```yaml
executor: custom
input: {}
steps:
- name: A
  script: echo "hello"
  vars:
    content:
      from: result.systemout
- name: B
  script: echo "{{.A.content}} world" # Does not works
output:
  content: '{{.B.systemout}}' # should be "hello world",  does not work with result.systemout too
```
```
> go run cmd/venom/main.go run tests/user_executor_custom_multisteps.yml --lib-dir tests/lib_custom/
 • testsuite with a user executor in custom dir which has multiple steps (tests/user_executor_custom_multisteps.yml)
        • testfoobar-multisteps-custom FAILURE
Testcase "testfoobar multisteps custom", step #0: Assertion "result.foobar ShouldEqual \"hello world\"" failed. expected: hello world  got: <nil> (tests/user_executor_custom_multisteps.yml:7)
exit status 2
```

**Comment by nqb** [comment]
Hello @lowlighter,

@JeGoi and I are interested by this feature.
If I'm not wrong, following example (provided above) is not correct:

```yaml
executor: custom
input: {}
steps:
- name: A
  script: echo "hello"
  vars:
    content:
      from: result.systemout
- name: B
  script: echo "{{.A.content}} world" # Does not works
output:
  content: '{{.B.systemout}}' # should be "hello world",  does not work with result.systemout too
```

because it's not possible to use `name:` attributes inside a custom executor environment because we only run "steps" and not testcases.

Could you confirm ? Perhaps @yesnault and @fsamin can confirm too.

**Comment by lowlighter** [comment]
@nqb yeah the syntax was updated when in #452, you can directly reference the variable without prefixing it.
The following should work:
```yaml
steps:
- script: echo "hello"
  vars:
    content:
      from: result.systemout
- name: B
  script: echo "{{.content}} world" # Does not works
```
