### ISSUE TITLE
feat: include a test from another file into a test suite with a default value or variable

### ISSUE THREAD

**Issue by JeGoi** [ovh/venom#457]
From https://github.com/ovh/venom/issues/320

> ```yaml
> executor: customA
> input:
>   myarg: {}
> steps:
> - script: echo "{{.input.myarg}}" > t.log
> - script: echo "{\"hello\":\"{{.input.myarg}}\"}"
>   assertions:
>   - result.code ShouldEqual 0
> output:
>    systemout: "{{.result.systemout}}"
>    systemoutjson.hello: "{{.result.systemoutjson.hello}}"
> ```

Is it possible to define a default value for .input.myarg if .input.myarg is not defined in the testsuite?
Something like

```yaml
executor: customA
input:
  myarg: {}
steps:
- script: echo "{{.input.myarg}}" > t.log
- script: echo "{\"hello\":\"{{.input.myarg | default \"Universe\"}}\"}"
  assertions:
  - result.code ShouldEqual 0
output:
   systemout: "{{.result.systemout}}"
   systemoutjson.hello: "{{.result.systemoutjson.hello}}"
```
or
```yaml
executor: customA
input:
  myarg: {}
steps:
- script: echo "{{.input.myarg}}" > t.log
- script: echo "{\"hello\":\"{{.input.myarg | default \".mydefault.value\"}}\"}"
  assertions:
  - result.code ShouldEqual 0
output:
   systemout: "{{.result.systemout}}"
   systemoutjson.hello: "{{.result.systemoutjson.hello}}"
```
and a testsuite that looks like that:
```yaml
name: testsuite with a user executor
testcases:
- name: testA
  steps:
  - type: customA
    myarg: {}
    info: 
    - result of customA is {{.result.systemoutjson.hello}}
    assertions:
    - result.systemoutjson.hello ShouldContainSubstring World
```
or
```yaml
name: testsuite with a user executor
testcases:
- name: testA
  steps:
  - type: customA
    info: 
    - result of customA is {{.result.systemoutjson.hello}}
    assertions:
    - result.systemoutjson.hello ShouldContainSubstring World
```

All tests end with:
```bash
          [trac] writing results/venom.log
executor "customA" is not implemented
```
Perhaps a yaml issue... wrong typo
Thanks

**Comment by JeGoi** [comment]
@nqb has found a solution.
```yaml
executor: customA
input:
  myarg: {
    "name": "default",
    "surname": "default2"
  }
steps:
- script: echo "{{.input.myarg.name}}" > t.log
- script: echo "{\"hello\":\"{{.input.myarg.name}} and {{.input.myarg.surname\"}"
  assertions:
  - result.code ShouldEqual 0
output:
   systemout: "{{.result.systemout}}"
   systemoutjson.hello: "{{.result.systemoutjson.hello}}"
```

```yaml
name: testsuite with a user executor
testcases:
- name: testA
  steps:
  - type: customA
     myarg: {
      "name": "world",
      "surname": "universe"
     }
     info: 
     - result of customA is {{.result.systemoutjson.hello}}
     assertions:
     - result.systemoutjson.hello ShouldContainSubstring world
     - result.systemoutjson.hello ShouldContainSubstring universe
```

```yaml
name: testsuite with a user executor
testcases:
- name: testA
  steps:
  - type: customA
     info: 
     - result of customA is {{.result.systemoutjson.hello}}
     assertions:
     - result.systemoutjson.hello ShouldContainSubstring default
     - result.systemoutjson.hello ShouldContainSubstring default2
```
