### ISSUE TITLE
feature request: add `stop-on-failure` support at steps level

### ISSUE THREAD

**Issue by lowlighter** [ovh/venom#459]
Currently the `stop-on-failure` seems to be only available at test-case level, but it would be nice to have them also at steps level.

Use case would be for multi-steps (both test and custom executor level) where one step depends on another one:
```yml
- steps:
  - type: exec 
    script: exit 1
    assertions:
      - result.code ShouldEqual 0
    vars:
      stdout:
        from: result.systemout
  - type: exec 
    script: echo '{{.stdout}}'
    assertions:
      - result.code ShouldEqual 0
```
