### ISSUE TITLE
Syntax issue with executors in executors, Venom v1.0.0

### ISSUE THREAD

**Issue by JeGoi** [ovh/venom#467]
Hi Venom Team,
I am trying to have an executor that can be used itself and in another executor.
Both executors have default values that can be overrides.
I am not sure I have the right syntax and have not been able to get from example and tests already in Venom.
I missing something... But what?
Please any help will be appreciated.

related structures:
https://github.com/ovh/venom/issues/451
https://github.com/ovh/venom/issues/457
https://github.com/ovh/venom/issues/320

Here are structures:

customA.yml
```yaml
executor: customA
input:
  myArg: "world2"
steps:
- type: customB
  myWord: "{{.input.myArg}}"
  vars:
    content:
      from: result.foobarB
- script: echo "hello {{.content}}"
  assertions:
  - result.code ShouldEqual 0
  - result.systemout ShouldContainSubstring "{{.input.myArg}}"
output:
  foobarA: "{{.result.systemout}}"
```

customB.yml
```yaml
executor: customB
input:
  myWord: "world"
steps:
- script: echo "{{.input.myWord}}"
  assertions:
  - result.code ShouldEqual 0
  - result.systemout ShouldContainSubstring "{{.input.myWord}}"
output:
  foobarB: "{{.result.systemout}}"
```

test_cases.yml
```yaml
testcases:
- name: customB_default
  steps:
  - type: customB
    assertions:
    - result.foobarb ShouldContainSubstring world

- name: customB_custom
  steps:
  - type: customB
    myWord: "universe"
    assertions:
    - result.foobarb ShouldContainSubstring universe

- name: customA_default
  steps:
  - type: customA
    assertions:
    - result.foobara ShouldContainSubstring world2
    - result.foobara ShouldContainSubstring hello

- name: customA_custom
  steps:
  - type: customA
    myArg: "universe"
    assertions:
    - result.foobara ShouldContainSubstring universe
    - result.foobara ShouldContainSubstring hello
```
