### ISSUE TITLE
Venom tries interpreting Go templates in my mock files so it fails

### ISSUE THREAD

**Issue by matcornic** [ovh/venom#473]
Hello,

I have a venom test which uses Smocker as mock server.

So one of the Venom test is: 

```yml
name: Test 1
version: "2"
testcases:
  - name: Init
    steps:
      - type: http
        method: POST
        url: "{{.mock_server}}/mocks"
        bodyFile: mocks/my.mocks.yml
        assertions:
          - result.statuscode ShouldEqual 200
```

The mock file that is send to the server is a YAML file containing a Go template that is useful for Smocker only. See https://smocker.dev/technical-documentation/mock-definition.html#format-of-dynamic-response-section

```yml
- request:
    path:
      matcher: ShouldMatch
      value: /path/\d+
    method: GET
  context:
    times: 1
  dynamic_response:
    engine: go_template
    script: >
      headers:
        Content-Type: [application/json]
      body: >
        {
          "id": "{{ index (splitList "/" .Request.Path) 2 }}"
        }
```

But since Venom 1.0, we are unable to launch this test because we get the error:

`unable to interpolate file [...] invalid template format "[...]": function "splitList" not defined`. 

It seems Venom is trying to run through Go templating while browsing for valid venom files. But this mock file is not a venom test, so it should not fail. 

I run the exact test suite with the venom yml file as argument.

There is maybe a way to escape the templating but I'd prefer an option or something ? Because with this behavior, it would be impossible to test Go templating features ^^. 

Thanks :)
