### ISSUE TITLE
feat: don't log a specific step or test case

### ISSUE THREAD

**Issue by nqb** [ovh/venom#476]
Hello,

When you use Venom with secrets, you may want to remove secrets from `venom.log`. It could be interesting to have a general setting like `log: False` which can be used to specify that output of a test case or a step should not be wrote into `venom.log`

**Comment by fsamin** [comment]
Hello,

For my understanding are the secret values some variables or are they data coming from testcase ?

Several users would like to hide some data from logs and output. I think about defining a list of variables names to consider as secret. Something like:

```
name: a test suite

secrets:
 - secret-value
 - secret-testcase.myvariable

testcases:
  - name: secret-testcase
    steps:
    - script: echo {{.secret-value}}
      assertions:
      - result.systemout ShouldEquals {{.secret-value}}
     vars:
      myvariable:
        from: result.systemout
```

In this example we assume that secret values will exist in variable `secret-value` (which will be set at runtime) and `secret-testcase.myvariable` (which will be exported during test execution).
It means that venom will hide those values in all logs, output and dump files.

would it be a solution for you needs ?
