### ISSUE TITLE
feat request: more detailed output result

### ISSUE THREAD

**Issue by lowlighter** [ovh/venom#485]
It would be nice to have a more detailed output which show all steps, like `range` steps and custom executor `steps`, the current one is pretty barebone and make it hard to know what has been run.

Example:
```diff
$ venom run test/ports.yaml 
• Testsuite
!  • Testcase FAILURE (1/2 tests succeded)
+    • 123 SUCCESS
+      • tcp SUCCESS
+      • udp SUCCESS
!    • 53 FAILURE (1/2 tests succeded)
+      • tcp SUCCESS
-      • udp FAILURE
```

```yaml
# Test suite
testcases:
  - name: Testcase
    steps:
      - type: checkPort
        host: 1.1.1.1
        range: [80, 443]
        port: '{{.value}}'

---
# Custom executor
executor: checkPort
steps:
  - name: {{.value.protocol}}
    type: exec
    script: nc -vz{{.value.arg}} {{.input.host}} {{.input.port}}
    range:
      - protocol: tcp
        arg: ""
      - protocol: udo
        arg: "u"
```
