### ISSUE TITLE
feat request: `skip` at step level

### ISSUE THREAD

**Issue by lowlighter** [ovh/venom#486]
If I'm not mistaken it's not possible to use `skip` at step level, it would be nice to be able to at least skip some tests in custom executors.

The main objective of custom executors (I think) is to reduce and factorize tests description, but sometimes you just need to skip out a step in a few case but it seems overkill to duplicate all steps and create another executor just to achieve the same 

Example:
```yaml
executor: test
input: 
  script1: true
  script2: true
steps:
  - type: exec
    script: script1
    skip:
      - {{.input.script1}} SouldEqual true
  - type: exec
    script: script2
    skip:
      - {{.input.script2}} SouldEqual true
```
