### ISSUE TITLE
Range with HTTP executor

### ISSUE THREAD

**Issue by righettod** [ovh/venom#494]
Hello,

Does the **range** keyword can be used with the **http** executor ?

I made the following test:

```yaml
name: Test
vars:
  target_site: "https://xxx.burpcollaborator.net"
testcases:    
- name: TestRange  
  steps:     
    - type: http
      # Cf https://github.com/ovh/venom/blob/master/tests/ranged.yml
      range:
        - actual: deploy.key
          expected: deploy.key
          index: 0
        - actual: package.json
          expected: package.json
          index: 1    
        - actual: package-lock.json
          expected: package-lock.json
          index: 2              
      method: GET
      url: "{{.target_site}}/{{.value.actual}}"
      skip_body: true
      timeout: 20
      assertions:
        - result.statuscode ShouldEqual 200
```

Perhaps I made a mistake but:
1. Only one request is send.
2. The placeholder is not replaced.

![image](https://user-images.githubusercontent.com/1573775/150937167-9a06cc63-c5d1-4577-ae22-e65e8517b765.png)

Did I miss something?

Thank you very much in advanced for your help 😃
