### ISSUE TITLE
Variables in skip statements are not case sensitive

### ISSUE THREAD

**Issue by emriver** [ovh/venom#522]
The variable case in skip assertions are not managed.
We must currently use the variable lowercase version to make it works.

Example:
```yaml
name: "Skip testsuite"
vars:
  Foo: true

testcases:
- name: dont-skip-this
  skip:
  - Foo ShouldBeTrue
  steps:
  - type: exec
    script: exit 0

- name: skip-this
  skip: 
    - foo ShouldBeTrue
  steps:
  - type: exec
    script: exit 0
```

```
 • Skip testsuite (test_skip.yml)
 	• dont-skip-this SKIPPED
 	• skip-this SUCCESS
```
