### ISSUE TITLE
Assertion ShouldBeGreaterThan fails

### ISSUE THREAD

**Issue by DonRenando** [ovh/venom#524]
Hello,

It seems that ShouldBeGreaterThan assertion with systemoutjson is not working.
I'm using venom v1.0.1 and with the following example:

```
- name: testA
  steps:
  - type: exec
    script: echo "{\"nb\":100}"
    assertions:
    - result.code ShouldEqual 0
    - result.systemoutjson.nb ShouldBeGreaterThan 29
```
I have the following error:

```
 testA FAILURE
Testcase "testA", step #0: Assertion "result.systemoutjson.nb ShouldBeGreaterThan 29" failed. expected: 100 greater than 29 but it wasn't (testsuite/certs/test.yml:13)
```
I have the impression that the comparison is an alphabetical comparison because if nb is equal to 99, the assertion works again.

the test case from #267, with systemout, works well
 
```
- name: testA
  steps:
  - type: exec
    script: echo 100
    assertions:
    - result.code ShouldEqual 0
    - result.systemout ShouldBeGreaterThan 29
```
If i use output from a testB step as input of another test step, it works well
- name: testB
  steps:
  - type: exec
    script: echo "{\"nb\":100}"
    vars:
      myvariable:
        from: result.systemoutjson.nb
- name: testC
  steps:
  - type: exec
    script: echo {{.testB.myvariable}}
    assertions:
    - result.code ShouldEqual 0
    - result.systemout ShouldBeGreaterThan 29

Thank you
