### ISSUE TITLE
http resolve to support scheme and port change

### ISSUE THREAD

**Issue by guoweis-work** [ovh/venom#525]
Currently, the resolver can handle something like this

```yaml
- type: http
  resolve:
    - siteA:8080:siteB
```
This changes from http://siteA:8080 to http://siteB:8080

In my use case, I need to change the port as well. 
```yaml
- type: http
  resolve:
    - https:siteA:443:http:siteB:8080
```
This changes from https://siteA:443 to http://siteB:8080

If I submit a PR for this, would you be open to take this? This will be an alternative, additional syntax of resolve.

If the scheme is too out of scope, what if just the port?

```yaml
- type: http
  resolve:
    - siteA:7070:siteB:8080
```
This changes from http://siteA:7070 to http://siteB:8080
