### ISSUE TITLE
In specific conditions, venom memory/result files/execution time increased drastically between 1.0.0-rc7 and 1.0.0

### ISSUE THREAD

**Issue by luphaz** [ovh/venom#533]
# Test context

Below is a representative test context aiming to illustrate the issue we are encountering since `venom v1.0.0`.
We did not encountered such issue while using `venom v1.0.0-rc.7`

**Venom memory consumptions, test result files size, and test execution time are increasing drastically.**

<details>
  <summary>Details about test context</summary>

## Given the following binary (1.0.0-rc.7 and 1.0.0)

```bash
curl https://github.com/ovh/venom/releases/download/v1.0.0/venom.darwin-amd64 -L -o./venom-1.0.0 && chmod +x ./venom-1.0.0
curl https://github.com/ovh/venom/releases/download/v1.0.0-rc.7/venom.darwin-amd64 -L -o./venom-1.0.0-rc.7 && chmod +x ./venom-1.0.0-rc.7

```

## Given the following custom executor stored in `lib_custom`:

```yaml
# // file lib_custom/foobar_http.yaml
executor: foobar_http
input:
  id: {}
  method: {}
  res: {}
  body: {}
steps:
  - type: http
    method: "{{.input.method}}"
    url: "https://jsonplaceholder.typicode.com/{{.input.res}}/{{.input.id}}"
    body: "{{.input.body}}"
    assertions:
      - result.statuscode ShouldEqual 200
output:
  statuscode: "{{.result.statuscode}}"
  body: "{{.result.bodyjson}}"
# // file lib_custom/foobar_http_get.yaml
executor: foobar_http_get
input:
  id: {}
  res: {}
steps:
  - type: foobar_http
    id: "{{.input.id}}"
    res: "{{.input.res}}"
    method: "GET"
    assertions:
      - result.statuscode ShouldEqual 200
output:
  statuscode: "{{.result.statuscode}}"
  body: "{{.result.bodyjson}}"
# // file lib_custom/foobar_http_get_user.yaml
executor: foobar_http_get_user
input:
  id: {}
steps:
  - type: foobar_http_get
    id: "{{.input.id}}"
    res: users
    assertions:
      - result.statuscode ShouldEqual 200
output:
  statuscode: "{{.result.statuscode}}"
  body: "{{.result.bodyjson}}"

```

## Given the following test suite:

```yaml
# // file user_executor_http_direct.yaml
name: user_executor_http
testcases:
  - name: call foobar_http_get_user
    steps:
      - type: foobar_http_get_user
        id: 1
        assertions:
          - result.bodyjson.id ShouldEqual 1

      - type: foobar_http_get_user
        id: 2
        assertions:
          - result.bodyjson.id ShouldEqual 2

      - type: foobar_http_get_user
        id: 3
        assertions:
          - result.bodyjson.id ShouldEqual 3

      - type: foobar_http_get_user
        id: 4
        assertions:
          - result.bodyjson.id ShouldEqual 4

      - type: foobar_http_get_user
        id: 5
        assertions:
          - result.bodyjson.id ShouldEqual 5

      - type: foobar_http_get_user
        id: 6
        assertions:
          - result.bodyjson.id ShouldEqual 6

      - type: foobar_http_get_user
        id: 5
        assertions:
          - result.bodyjson.id ShouldEqual 5

      - type: foobar_http_get_user
        id: 7
        assertions:
          - result.bodyjson.id ShouldEqual 7

      - type: foobar_http_get_user
        id: 8
        assertions:
          - result.bodyjson.id ShouldEqual 8

      - type: foobar_http_get_user
        id: 9
        assertions:
          - result.bodyjson.id ShouldEqual 9

      - type: foobar_http_get_user
        id: 10
        assertions:
          - result.bodyjson.id ShouldEqual 10
```

## Given the following executions:

```bash
time ./venom-1.0.0-rc.7 run --lib-dir tests/lib_custom tests/user_executor_http.yml -vv --format xml --output-dir results/1.0.0-rc.7

# before running this, you might want to grab some ☕️☕️, and free some disk space (like a lot)
# the below command generate more than 25GB of data, before I needed to exit the command
# it took around 20 minutes on my machine 
# similar behaviour will be encountered without using the "-vv" flag
# 663.20s user 300.35s system 79% cpu 20:08.55 total

time ./venom-1.0.0 run --lib-dir tests/lib_custom tests/user_executor_http.yml -vv --format xml --output-dir results/1.0.0

```
</details>

# Behaviour encountered

## Venom v1.0.0 consume a huge amount of memory

On my machine, the process seen more than 100GB trying to perform `user_executor_http.yml`

![image](https://user-images.githubusercontent.com/7045919/162979815-2ad77f46-eadf-444f-87bf-d86e7a093952.png)

## Venom v1.0.0 dump files are significantly larger

File results:

```bash
# du -sh ./results/*     
 25G    ./results/1.0.0 # stopped before completion
452K    ./results/1.0.0-rc.7 
```

## Venom v1.0.0 test execution is slower

```bash
time ./venom-1.0.0-rc.7 run --lib-dir tests/lib_custom tests/user_executor_http.yml -vv --format xml --output-dir results/1.0.0-rc.7
# 0.60s user 0.28s system 38% cpu 2.273 total
time ./venom-1.0.0 run --lib-dir tests/lib_custom tests/user_executor_http.yml -vv --format xml --output-dir results/1.0.0
# 663.20s user 300.35s system 79% cpu 20:08.55 total

```

# Expectations

Venom v1.x.x memory consumption stays similar `v1.0.0-rc.7`
Venom test results file size stays similar as `v1.0.0-rc.7`
Venom test execution time stays similar as `v1.0.0-rc.7`

# Potential root cause

We tracked down the issue to the following commit (that append computed vars to next test cases):
* https://github.com/ovh/venom/commit/fe3d592ab1b22f53820f1aaffe8e49e4196f8849

However, in general and prior to this commit, test output files are full of escaping characters `\` mostly due to successive escape of JSON string, escaping happening in [`go-dump`](github.com/fsamin/go-dump) library and inside venom directly.

<details>
  <summary>pprof files to track down the root cause of the memory consumption</summary>
  
![out-final3](https://user-images.githubusercontent.com/7045919/162985061-5db3fc23-ee76-44fd-9c0b-a8ba6ac990a4.png)

</details>

# Potential solution

On our side, we were already using a similar capability inside executor to reference executor vars, as of today we were not able to find another option than removing the [added](https://github.com/ovh/venom/blob/777c4444e228622b10151274acf52f7ef9fa5258/process_testcase.go#L294) line

<details>
  <summary> Illustrate how we were doing what the commit tried to achieve</summary>
  
### Before

```yaml
executor: foobarcustommultisteps
input: {}
steps:
- script: echo "hello"
  vars:
    content:
      from: result.systemout
- script: echo "{{.content}} world"
output:
  foobar: "{{.result.systemout}}"
```

### After

```yaml
executor: foobarcustommultisteps
input: {}
steps:
- script: echo "hello"
  vars:
    content:
      from: result.systemout
- script: echo "{{.foobarcustommultisteps.content}} world"
output:
  foobar: "{{.result.systemout}}"
```
</details>
