### ISSUE TITLE
[http executor] Assertion ShouldBeLessThanOrEqualTo fails v1.0.1

### ISSUE THREAD

**Issue by florian-chevalier** [ovh/venom#548]
Hello,
It seems that ShouldBeLessThanOrEqualTo assertion with result.bodyjson is not working.
Example : 
```
testcases:
  - name: get-list-dictionaries
    steps:
      - type: http
        basic_auth_user: 'login'
        basic_auth_password: 'password'
        headers:
          accept: application/json
        method: GET
        url: 'some-request'
        assertions:
          - result.statuscode ShouldEqual 200
          - result.bodyjson.numberofelements ShouldBeLessThanOrEqualTo 10
```
Result : 
```
Assertion "result.bodyjson.numberofelements ShouldBeLessThanOrEqualTo 10" failed. expected: 3 less than or equals to 10 but it wasn't
```

Thank you very much in advanced.
