### ISSUE TITLE
Missing escaping of "\" in json

### ISSUE THREAD

**Issue by francoisgognet** [ovh/venom#581]
When using a json whose one value is itself an escaped json, venom breaks 

### way to reproduce 
- venom file : 

```
name: "parsing"
testcases:
  - name: "test"
    steps:
      - type: readfile
        path: json_file.json
      - script: echo {{.result.content }}
```

- json_file.json : 
`{"foo": "{\"bar\":\"baz\"}"}`

### Expected behavior

- in the logs, I get the following : 
{\"script\":\"echo {\\\"foo\\\": \\\"{\\\\\"bar\\\\\":\\\\\"baz\\\\\"}\\\"}\"}
- what I expected : 
{\"script\":\"echo {\\\"foo\\\": \\\"{\\\\\\\"bar\\\\\\\":\\\\\\\"baz\\\\\\\"}\\\"}\"}

- what we actually have (unescaped once) : 
{"script":"echo {\"foo\": \"{\\"bar\\":\\"baz\\"}\"}"} => invalid json
- what I actually expect (unescaped once) : 
{"script":"echo {\"foo\": \"{\\\"bar\\\":\\\"baz\\\"}\"}"}
