### ISSUE TITLE
Executor OVHAPI ignore noAuth

### ISSUE THREAD

**Issue by YoannAtOVH** [ovh/venom#585]
Hello,

A ovhapi step require application(Key|Secret) and consumerKey even if noAuth:
```
name: MyTestSuite

testcases:
- name: test case 1
  steps:

  - type: ovhapi
    endpoint: 'ovh-eu'
    noAuth: true
    method: GET
    path: /auth/time
    retry: 3
    delay: 2
```

Current output:
```
 • MyTestSuite (debug_venom.yml)
 	• test-case-1 FAILURE
Testcase "test case 1", step #0: missing application key, please check your configuration or consult the documentation to create one (debug_venom.yml:8)
```

❯ venom version
Version venom: v1.0.1

Regards,
