### ISSUE TITLE
Print info in current "step" before assertions

### ISSUE THREAD

**Issue by ColinHuang** [ovh/venom#597]
In this case, `result 2` will still print the bodyjson of `result 1`. 
Is there a way to make `result 2` print the bodyjson of `test2`? 

Hope the `result 2` will be printed even if the test of `test2` failed.

```yaml
testcases:
- name: test A
  steps:
  - type: http
    method: POST
    url: {{.url}}/test1
    timeout: 5
    info: result 1 {{.result.bodyjson}}
    assertions:
    - result.statuscode ShouldEqual 200
  - type: http
    method: GET
    url: {{.url}}/test2
    timeout: 5
    retry: 3
    delay: 2
    info: result 2 {{.result.bodyjson}}
    assertions:
    - result.statuscode ShouldEqual 200
```
