### ISSUE TITLE
Assertions on null JSON values

### ISSUE THREAD

**Issue by bchaillou-ovh** [ovh/venom#614]
Hi,

I have the same issue that this person : https://github.com/ovh/venom/issues/265
I tested on v1.0.1 and v1.1.0.
Given the following bodyjson content:
```json
"bodyjson": [
   {
    "foo": null,
   }
]
```
I would like to make an assertion about this `null` value, something like `result.bodyjson.bodyjson0.foo ShouldBeNil`.
However, the only assertion which works is `result.bodyjson.bodyjson0.foo ShouldEqual ""`, as if deserializing the body had replaced my `null` object with an empty string. Or the other assertion which works is `result.bodyjson.bodyjson0.foo.__type__ ShouldEqual <nil>`.

**Comment by fsamin** [comment]
Hi,
Do you mean that assertion `ShouldBeNil` does not work as expected ?
Do you have a reproducer ?

**Comment by bchaillou-ovh** [comment]
Hi François,

Yes, `ShouldBeNil` does not work as expected?
A reproducer ? What do you mean ? Yes, I can reproduce the issue easily.

**Comment by bchaillou-ovh** [comment]
Success:
```yaml
version: "2"
name: TestSuite
testcases:
  - name: test
    steps:
      - type: exec
        script: >
          echo '{"test": null}'
        assertions:
          - result.systemoutjson.test.__type__ ShouldEqual <nil>
```
Failure:
```yaml
version: "2"
name: TestSuite
testcases:
  - name: test
    steps:
      - type: exec
        script: >
          echo '{"test": null}'
        assertions:
          - result.systemoutjson.test ShouldBeNil
```
