### ISSUE TITLE
info provides previous user executor information if same user executor is run twice

### ISSUE THREAD

**Issue by sixstone-qq** [ovh/venom#622]
Provided this test:
```yaml
name: foo
testcases:
- name: same_user_executor_twice
  steps:
  - type: a_user_executor
    in: "First call"
    info: Info "{{.result.out}}"
    assertions:
      - result.out ShouldEqual "First call"
  - type: a_user_executor
    in: "Second call"
    info: Info "{{.result.out}}"
    assertions:
      - result.out ShouldEqual "Second call"
```
With this user executor:
```yaml
executor: a_user_executor
input:
  in: {}
steps:
  - type: script
    exec: echo "{{.input.in}}"
output:
  out: {{.input.in}}
```
The output from venom v1.1.0 is:
```
❯ venom run foo.yml
          [trac] writing results/venom.log
 • foo (foo.yml)
        • same_user_executor_twice
                • a_user_executor PASS
                • a_user_executor PASS
                  [info] Info "First call" (foo.yml:7)
                  [info] Info "First call" (foo.yml:12)
                  [trac] writing results/foo.same_user_executor_twice.step.0.0.dump.json
                  [trac] writing results/foo.same_user_executor_twice.step.1.0.dump.json
Writing file results/test_results_foo.xml
final status: PASS
```
Note the second Info from line 12 must output `Second call` and not `First call`.

Let me know if you need any help on this?

Thanks for this amazing project!
