### ISSUE TITLE
Add new JSON equality operators

### ISSUE THREAD

**Issue by Thiht** [ovh/venom#633]
Hi!

I propose to add 4 new assertion operators: `ShouldEqualJSON`, `ShouldEqualJSONFile`, `ShouldContainJSON`, `ShouldContainJSONFile`.

These operators work on JSON, so they ignore whitespace, key ordering, [comments](https://json5.org/#comments) and other no-ops.

- `ShouldEqualJSON` asserts that 2 JSON documents are equal, according to the above rule.

```
// TRUE
{
  "bar": 1,
  "foo": true
} ShouldEqualJSON { "foo": true, "bar": 1 }
```

- `ShouldEqualJSONFile`: same as `ShouldEqualJSON`, but reads `expected` from a file.

```
result.body ShouldEqualJSONFile ./expected.json
```

I mentioned allowing JSON comments above (supported in [JSON5](https://json5.org/) because it would be extremely useful with files, to be allowed to add details on some expected values.

Now in my opinion, 2 more interesting operators are `ShouldContainJSON` and `ShouldContainJSONFile`. They would work the same as `ShouldEqualJSON`, `ShouldEqualJSONFile`, except that they could be used in all cases where some keys are unpredictable: random values, generated IDs (UUIDs, etc.), timestamps... Example:

```
// TRUE
{ "id": "63e60deaf57eda4b4e4c511e", "timestamp": 1676311874, "status": "ok" } ShouldContainJSON { "status": "ok" }

// We can still add more assertions below if we want
result.bodyjson.id ShouldNotBeEmpty
result.bodyjson.timestamp ShouldBeGreaterThan 0
```

What do you think? I think `ShouldContainJSON`/`ShouldContainJSONFile` are a bit more challenging to implement, but would be extremely useful. They would help get rid of this situation when handling big JSONs:

```
result.bodyjson.a ShouldEqual xxx
result.bodyjson.b ShouldEqual xxx
result.bodyjson.c ShouldEqual xxx
// ...
result.bodyjson.x ShouldEqual xxx
result.bodyjson.y ShouldEqual xxx
result.bodyjson.z ShouldEqual xxx
```

Edit: I just found this lib which does exactly that, so no need to implement diffing algorithms: https://pkg.go.dev/github.com/nsf/jsondiff#section-readme

> At the moment it can detect a couple of types of differences:
> - FullMatch - means items are identical.
> - SupersetMatch - means first item is a superset of a second item.
> - NoMatch - means objects are different.

**Comment by fsamin** [comment]
Hi @Thiht ,
I do like `ShouldEqualJSON` and `ShouldEqualJSON`, it would be very helpful 
i'm not sure about ShouldContainJSONFile and ShouldEqualJSONFile. We could achieve the same goal with a readfile step or something like that

**Comment by Thiht** [comment]
Hi @fsamin,

I thought of using the readfile, but I feel like it's a lot of boilerplate and a bit hard to write. If we compare: 

<table>
<tr>
	<th>

With `readfile`

</th>
	<th>

With `ShouldContainJSONFile`

</th>
<tr>
<td>

```yml
testcases:
  - name: my test
    steps:
      - type: readfile
        path: ./expected.json
        vars:
          expected:
            from: result.content

      - type: xxx
        # ...
        assertions:
          - result.body ShouldContainJSON {{ .mytest.expected }}
```

</td>
<td>

```yml
testcases:
  - name: my test
    steps:
      - type: xxx
        # ...
        assertions:
          - result.body ShouldContainJSONFile ./expected.json
```

</td>
</table>

Right version gives, in my opinion, a way better developer experience:

- no need to use `readfile`+vars, so we save 5 lines. I also don't regularly use `readfile` or variables, so it took me a bit of time to write the full readfile step correctly (I think)

- variables from other steps are not easy to use. In this case, it's referenced `mytest` because the test case name is `my test`, but sometimes it's not easy to predict or write. If my test case is named `Check the result of the /version API` it'll be hard to use the variable

It would be the only operator reading the expected from a file, but I think the ease of use is worth it in this case.

**Comment by Thiht** [comment]
A third solution I just thought of, if you don't want assertion operators to directly depend on a file: what about a new "variable helper" `readFile`? Something like:

```yml
testcases:
  - name: my test
    steps:
      - type: xxx
        # ...
        assertions:
          - result.body ShouldContainJSON {{ "./expected.json" | readFile }} 
```

This way it's as short as `ShouldContainJSONFile` but more generic. Not sure if it's possible though
