### ISSUE TITLE
feat: breakpoints

### ISSUE THREAD

**Issue by yesnault** [ovh/venom#65]
venom run --breakpoint [id_step]
--> run interactive mode
--> "debug" for output var
--> "update" [varname] [value] to update a variable
--> "run" for continue test

**Comment by yesnault** [comment]
fixed with https://github.com/ovh/venom/commit/47441c3f614fbe9b1aaa121aae611d3bf1b4c16e
keyword info:

```yml
name: Exec testsuite
testcases:
- name: testA
  steps:
  - type: exec
    script: echo 'foo with a bar here'
    info:
      - this a first info
      - and a second...
    assertions:
    - result.code ShouldEqual 0
    - result.timeseconds ShouldBeLessThan 1
    vars:
      myvariable:
        from: result.systemout
        regex: foo with a ([a-z]+) here
```
