### ISSUE TITLE
Skip a step in range/loop doesn't work

### ISSUE THREAD

**Issue by aabouzaid** [ovh/venom#651]
Hi :wave:

Thanks for this nice test suite, it's pretty useful. I use Venom in [Camunda Platform Helm charts](https://github.com/camunda/camunda-platform-helm) integration tests.

**Use case:**
I want to control the loop steps conditionally in case some services are not available for testing.
So some of the loop items work, and some are skipped.

**The problem:**
It looks like the loop vars are not accessible in `skip` part.

Example:

```
testcases:
- name: TEST
  steps:
  - name: "{{ .value.component }}"
    type: http
    range:
    - component: A
      url: http://service-a/health
      skip: 1
    - component: B
      url: http://service-b/health
      skip: 1
    - component: C
      url: http://service-c/health
      skip: 0
    method: GET
    url: "{{ .value.url }}"
    retry: 3
    delay: 10
    skip:
    - "{{ .value.skip }} ShouldNotEqual 1"
    assertions:
    - result.statuscode ShouldEqual 200
```
I get the following:
```
• A (range=0) FAIL
 assertion not supported
• B (range=1) FAIL
 assertion not supported
• C (range=2) FAIL
 assertion not supported
```
The same behaviour would be if I used `{{ .index }}`, the loop vars are not accessible.

**Info:**
- Version venom: v1.1.0
