### ISSUE TITLE
Skip assertions should preserve the case

### ISSUE THREAD

**Issue by aabouzaid** [ovh/venom#654]
While using `skip` testcase/step I just realized that skip assertions don't preserve the case. It's exactly as in #527 but looks like the implementation wasn't done for `skip` assertions.

```
name: "Skip testsuite"
vars:
  fooVar: bar

testcases:

- name: this-will-be-skipped
  skip: 
  - fooVar ShouldNotBeEmpty
  steps:
  - type: exec
    script: exit 0

- name: this-will-run-and-pass
  skip: 
  - foovar ShouldNotBeEmpty
  steps:
  - type: exec
    script: exit 0
```
