### ISSUE TITLE
error converting YAML to JSON

### ISSUE THREAD

**Issue by fehrnah** [ovh/venom#655]
Venom version: v1.1.0

This is similar to #396 which was fixed in v1.1.0

When extracting a JSON containing an encoded JSON in a value from a webpage we get the error:
`unable to unmarshal: error converting YAML to JSON: yaml: line 11: did not find expected ',' or '}'`

The step where the error happens:
```yaml
  - type: web
    action:
      find: pre#json_container
    vars:
      my_variable:
        from: result.text
```

Content of the JSON:
```json
{
    "encoded_field": "{\"value\": [\"v1\", \"v2\"]}" 
}
```
