### ISSUE TITLE
bug: TC logging result is showing previous step http response

### ISSUE THREAD

**Issue by ivan-velasco** [ovh/venom#658]
Logging in a test case with multiple http requests is not showing latest response when using `{{.result.bodyjson}}`

```yaml
testcases:
- name: LOGGING
  steps:
- type: http
    method: POST
    bodyFile: "a"
  info: 
    - "REQUEST body {{.result.request}}"
    - "RESPONSE body {{.result.bodyjson}}"

- type: http
  method: PATCH
  body: >-
          {
              "property: "value"
          }
  info: 
   - "REQUEST body {{.result.request}}"
   - "RESPONSE body {{.result.bodyjson}}"
```
