### ISSUE TITLE
bug : variable assignment in an executor

### ISSUE THREAD

**Issue by fokion** [ovh/venom#659]
Lets say you have an executor and you want to localise the scope of a variable as you may want to reuse it somewhere else without the prefix `.input`.

The assumption is that the following step should work but it does not

```yaml
  - name: "localise variable user"
    vars:
      user.uuid:
        from: '{{.input.user.uuid}}'
```

On the other hand its working properly 

```yaml
  - name: "localise variable user"
    script: |
      echo "{{.input.user.uuid}}"
    vars:
      user.uuid:
        from: result.systemout

```
