### ISSUE TITLE
Repurpose .venomrc into an environment-aware config file

### ISSUE THREAD

**Issue by x80486** [ovh/venom#683]
I've been trying to configure `Venom` to use multiple environments with different configurations in order to run the same test suites in different environments.

I've also found out that it's quite tricky to use different files to store variables that change between environments. It gets even more complex when testing locally and reusing some of the other values.

I think repurposing `.venomrc` into an environment-aware config file would solve this problem. For instance, say it's `config.yaml` by default (instead of `.venomrc`), the file could look like:

```yaml
environment: default
format: xml
lib_dir: lib
output_dir: results
stop_on_failure: true
variables:
  var1: val1
  var2: val2
  var3: val3
verbosity: 1
---
environment: local
format: json
stop_on_failure: false
variables:
  var1: val1_override_for_local
---
environment: test
variables:
  var1: val1_override_for_test
  var2: val2_override_for_test
  var3: val3_override_for_test
---
environment: integration
variables:
  var1: val1_override_for_integration
  var2: val2_override_for_integration
  var3: val3_override_for_integration
```

`Venom` could then pick up the correct environment based on a flag `--venom.environment=test`.

> Ideas taken from [Quarkus Configuration Reference Guide](https://quarkus.io/guides/config-reference).

If you are able to add a `.env` file in the chain, it will be even better, but I guess it might not be strictly required. It's worth to note that if taken into consideration, the values should take references to environment variables and be able to expand them correctly.
