### ISSUE TITLE
Support Kafka headers in consumer/producer

### ISSUE THREAD

**Issue by skateinmars** [ovh/venom#690]
Hello,

I would like for kafka headers to be supported, both reading them when consuming or when producing messages.
Sarama already supports it, cf https://github.com/shopify/sarama/blob/v1.20.1/async_producer.go#L177C12-L177C24 on the producer side for instance.

The yaml config could be extended:

```
name: My Kafka testsuite
version: "2"
testcases:
- name: Kafka test
  description: Test Kafka
  steps:
  - type: kafka
    clientType: producer
    withSASL: true
    withTLS: true
    user: "{{.kafkaUser}}"
    password: "{{.kafkaPwd}}"
    addrs:
      - "{{.kafkaHost}}:{{.kafkaPort}}"
    messages:
    - topic: test-topic
      key: "{{.entityID}}"
      headers:
        - key: "X-Internal-ID"
          value: "0168a1e7-cdc6-4820-981b-f6e381b59003"
      value: |
        {
          "Foo": "Bar"
        }
```

Thanks for your work on this project!
