### ISSUE TITLE
Custom executor output seems to not be working as expected

### ISSUE THREAD

**Issue by lorefnon** [ovh/venom#712]
Hello, thanks for creating and open sourcing this library. This looks like a good fit for a use case we have. 

I am trying to define a custom executor for json rpc requests:

```yaml
executor: jsonrpc
input: 
  service: {}
  method: {}
  params: {}
steps:
  - type: http
    url: "{{.api.base_url}}/rpc/{{.input.service}}"
    method: POST
    body: '{ "jsonrpc": "2.0", "method": "{{.input.method}}", "params": {{.input.params | toJSON "." | substr 0 -1 }} }'
    headers:
      Content-Type: application/json
    assertions:
      - result.statuscode ShouldEqual 200
      - result.bodyjson.jsonrpc ShouldEqual "2.0"
      - result.bodyjson.error ShouldBeNil
    vars:
      returned: 
        from: "result.bodyjson.result"
output:
  res: '{{ .returned }}'
```

While the assertions defined in the executor work as expected, the output does not seem to be interpolated correctly. 

For an example usage: 

```yaml
name: "Custom Workflow"
testcases:
      - type: jsonrpc
        service: test
        method: testMethod
        params: 
          - foo: "foo"
        assertions:
          - result.resjson.bar ShouldNotBeNil
```

The `ShouldNotBeNil` always fails even though the service does return an object like `{ "bar": "baz" }`. 

When I look at the dump with (`-vv`)

```json
{
 "variables": {
    ...
 },
 "step": {
  "assertions": [
   "result.resjson.bar ShouldNotBeNil"
  ],
  "method": "testMethod",
  "params": [
   {
    "foo": "foo"
   }
  ],
  "service": "test",
  "type": "jsonrpc"
 },
 "result": {
  "__len__": 1,
  "__type__": "Map",
  "result": {
   "res": "{{ .returned }}"
  },
  "result.__Len__": 1,
  "result.__Type__": "Map",
  "result.res": "{{ .returned }}"
 }
}
```

The uninterpolated "{{ .returned }}" looks suspicious but in venom.log I don't see any explicit error.

Please advise what is the right way to approach this. Thanks in advance.

**Comment by ivan-velasco** [comment]
Can you update vars from statement?
```yml
vars:
   returned: 
     from: "result.bodyjson"
```

**Comment by ivan-velasco** [comment]
@lorefnon Can you try like this? (quotes changed slightly and indent also on output)
```yml
  vars: 
    returned:
      from: result.bodyjson.result

output:
    res: "{{.returned}}"
```
Could you also  run in verbose mode 2? `-vv` to see if the value is available when running the executor?
