### ISSUE TITLE
(bug) Subassertions are not rendered in reports

### ISSUE THREAD

**Issue by bcecchinato** [ovh/venom#754]
Hello !

I've got the following assertions :
```
        assertions:
          - result.statuscode ShouldEqual 200
          - result.bodyjson.board-current ShouldEqual 17999
          - result.bodyjson.board-current-residual ShouldEqual 99
          - result.bodyjson.detection-threshold ShouldEqual 69
          - result.bodyjson.emergency-mode ShouldEqual "LOWER_FIRST"
          - result.bodyjson.output-current.0 ShouldEqual 3999
          - result.bodyjson.output-current.1 ShouldEqual 3998
          - result.bodyjson.output-current.2 ShouldEqual 3998
          - result.bodyjson.output-current.3 ShouldEqual 3998
          - result.bodyjson.output-current.4 ShouldEqual 3998
          - result.bodyjson.output-current.5 ShouldEqual 3998
          - result.bodyjson.output-current.6 ShouldEqual 3998
          - result.bodyjson.output-current.7 ShouldEqual 3998
          - result.bodyjson.output-current-residual.0 ShouldEqual 19
          - result.bodyjson.output-current-residual.1 ShouldEqual 18
          - result.bodyjson.output-current-residual.2 ShouldEqual 18
          - result.bodyjson.output-current-residual.3 ShouldEqual 18
          - result.bodyjson.output-current-residual.4 ShouldEqual 18
          - result.bodyjson.output-current-residual.5 ShouldEqual 18
          - result.bodyjson.output-current-residual.6 ShouldEqual 18
          - result.bodyjson.output-current-residual.7 ShouldEqual 18
          - result.bodyjson.rearm-timeout ShouldEqual 299
          - or:
            - and:
              - SPDU-20-4008-TC01-Details.report.firmware ShouldNotStartWith "BIN_V5.0"
              - result.bodyjson.backoff-timeout ShouldEqual 0
              - result.bodyjson.output-priority.0 ShouldEqual 0
              - result.bodyjson.output-priority.1 ShouldEqual 0
              - result.bodyjson.output-priority.2 ShouldEqual 0
              - result.bodyjson.output-priority.3 ShouldEqual 0
              - result.bodyjson.output-priority.4 ShouldEqual 0
              - result.bodyjson.output-priority.5 ShouldEqual 0
              - result.bodyjson.output-priority.6 ShouldEqual 0
              - result.bodyjson.output-priority.7 ShouldEqual 0
            - and:
              - SPDU-20-4008-TC01-Details.report.firmware ShouldNotStartWith "BIN_V5.1"
              - result.bodyjson.backoff-timeout ShouldEqual 0
              - result.bodyjson.output-priority.0 ShouldEqual 0
              - result.bodyjson.output-priority.1 ShouldEqual 0
              - result.bodyjson.output-priority.2 ShouldEqual 0
              - result.bodyjson.output-priority.3 ShouldEqual 0
              - result.bodyjson.output-priority.4 ShouldEqual 0
              - result.bodyjson.output-priority.5 ShouldEqual 0
              - result.bodyjson.output-priority.6 ShouldEqual 0
              - result.bodyjson.output-priority.7 ShouldEqual 0
            - and:
              - SPDU-20-4008-TC01-Details.report.firmware ShouldNotStartWith "BIN_V5.0"
              - SPDU-20-4008-TC01-Details.report.firmware ShouldNotStartWith "BIN_V5.1"
              - result.bodyjson.backoff-timeout ShouldEqual 299
              - result.bodyjson.output-priority.0 ShouldEqual 0
              - result.bodyjson.output-priority.1 ShouldEqual 1
              - result.bodyjson.output-priority.2 ShouldEqual 1
              - result.bodyjson.output-priority.3 ShouldEqual 1
              - result.bodyjson.output-priority.4 ShouldEqual 1
              - result.bodyjson.output-priority.5 ShouldEqual 1
              - result.bodyjson.output-priority.6 ShouldEqual 1
              - result.bodyjson.output-priority.7 ShouldEqual 1
```

The report will render all "root" assertions properly, but the and/or blocs are rendered as `[object Object]`. It would be better to show the assertions that have been validated/skipped instead.
