### ISSUE TITLE
(bug) Unable to assert test case on venom.datetime

### ISSUE THREAD

**Issue by bcecchinato** [ovh/venom#759]
Hello !

This test fails every time :
```
---
name: "test"
testcases:
  - name: "Bad RFC"
    steps:
      - name: "Say hello"
        type: exec
        script: echo "Hello !"
        delay: 60
        assertions:
          - result.code MustEqual 0
          - venom.datetime MustHappenOnOrAfter "300 seconds from now"
        retry: 1000
        retry_if:
          - result.code MustEqual 0
          - venom.datetime MustHappenOnOrBefore "300 seconds from now" 
```
The result output is :
```
 • test (test.yml)
     • Bad-RFC
         • Assert Flip Resistor FAIL
           Testcase "Bad RFC", step #0-0: retry conditions not fulfilled, skipping 1000 remaining retries (test.yml:8)
           Testcase "Bad RFC", step #0-0: Assertion "venom.datetime MustHappenOnOrAfter \"300 seconds from now\"" failed. invalid date provided with %!q(<nil>) not in RFC3339 format or humanize format (test.yml:12)
           Testcase "Bad RFC", step #0-0: At least one required assertion failed, skipping remaining steps (test.yml:8)
           0 other steps were skipped 
```

The variable venom.datetime doesn't look to be populated.
