### ISSUE TITLE
(enhancement) extend range to cover a test case with multiple steps

### ISSUE THREAD

**Issue by ivan-velasco** [ovh/venom#760]
Currently range is only supported at the individual step level only

**Proposal**: If present at `steps` level then each step will be part of range loop
```yml
  - name: read data file
    steps:
    - type: readfile
      path: testdata/test.json
      vars: 
        data:
          from: result.contentjson

  - name: run crud operations
    range: '{{.data}}'
    steps:
    - type: http
      method: GET
    - type: http
      method: PATCH
    - type: http
      method: GET
```
