### ISSUE TITLE
invalid session id with web executor

### ISSUE THREAD

**Issue by FloRichardAloeCorp** [ovh/venom#780]
Hello I'm running into an issue while trying to run web executor.

Execution env:
* MacOS Sonoma Version 14.2.1 (23C71)
* chromedriver version: 123.0.6312.58
* Chromium version: 123.0.6312.58

 I have the following error:

```
Testcase "TestCase Google search", step #0: failed to navigate: request unsuccessful: invalid session id (test/venom/suites/test_web.yml:15)
```

The test file look like this:
```yaml
name: Test web

vars:
  web:
    driver: chrome
    logLevel: DEBUG
    driverPath: "/usr/local/bin/chromedriver"
    binaryPath: "/Applications/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing"
    debug: true

testcases:
  - name: TestCase Google search
    steps:
      - type: web
        action:
          navigate:
            url: https://www.google.fr

```
Here is the stack trace: 
[venom.log](https://github.com/ovh/venom/files/14671345/venom.log)

Is this a common issue on MacOS ?
