### ISSUE TITLE
[bug] venom variable interpolation not working as expected in test file

### ISSUE THREAD

**Issue by mxm-tr** [ovh/venom#788]
I'm using Venom 0.27 and I have a test file that contains the following vars:

```yaml
vars:
  kubeconfig.path:          '/tmp/default'
  kubecmd:                  'kubectl --kubeconfig={{.kubeconfig.path}}' 
```

When I run this test file with `--var kubeconfig.path=/tmp/test`, I expect the output to be:

```
kubeconfig.path=/tmp/test
kubecmd="kubectl --kubeconfig=/tmp/test" 
```
(This is what I get in 0.27)

However, the output with the current version is:
```
kubeconfig.path=/tmp/test
kubecmd="kubectl --kubeconfig=/tmp/default" 
```

As you can see, the `kubecmd` variable is not being interpolated correctly. I understand that Venom may have changed the behavior of variable interpolation in version 0.27, but I'm not sure why the interpolation is not working as expected in this case.

Do you know if this behavior is expected and/or how to fix it?

Thank you!
