### ISSUE TITLE
Fixtures

### ISSUE THREAD

**Issue by bersace** [ovh/venom#797]
Degemer,

Que pensez-vous d'implémenter une système de fixtures ? L'idée est de pouvoir gérer le nettoyage de ressources. À l'instar de pytest, ce serait chouette qu'une fixture puisse dépendre d'autres fixtures. Voici une idée de YAML.

``` yaml
name: My suite
fixtures:
  myfix:
    scope: case # run/suite/case
    setup:
      - exec: ...
      - command: []
      - type: sql
        ...
    teardown:
      - ...
  autrefix:
    fixtures: [myfix]
    setup: ...
testcases:
  - name: mytest
    fixtures: [autrefix]
    steps: ...
```

Dans l'idée, une fixture est:

- une liste de steps de setup
- une liste de steps de teardown
- un périmètre pour déterminer quand sont exécuté ssetup et teardown
- une liste d'autres fixtures à hériter

À mon avis, ça serait bien qu'un fixtures produise des variables.

Qu'en pensez-vous ?

Étienne
